; Collections$ReverseComparator2-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:39:42 CDT 2014.
;

(defconst *java.util.Collections$ReverseComparator2*
 (make-class-def
      '(class "java.util.Collections$ReverseComparator2"
            "java.lang.Object"
            (constant_pool
                        (LONG 4374092139857)
                        (INT -2147483648))
            (fields
                        (field "serialVersionUID" long (accessflags  *class*  *final*  *private*  *static* ) 0)
                        (field "cmp" (class "java.util.Comparator") (accessflags  *class*  *final* ) -1)
                        (field "$assertionsDisabled" boolean (accessflags  *class*  *final*  *static* ) -1))
            (methods
                        (method "<init>"
                              (parameters (class "java.util.Comparator"))
                              (returntype . void)
                              (accessflags  *class* )
                              (code
                                   (max_stack . 2) (max_locals . 2) (code_length . 28)
                                   (parsedcode
                                      (0 (aload_0)) 
                                      (1 (invokespecial (methodCP "<init>" "java.lang.Object" () void))) 
                                      (4 (getstatic (fieldCP "$assertionsDisabled" "java.util.Collections$ReverseComparator2" boolean))) 
                                      (7 (ifne 22))  ;;to TAG_0
                                      (10 (aload_1)) 
                                      (11 (ifnonnull 22))  ;;to TAG_0
                                      (14 (new (class "java.lang.AssertionError"))) 
                                      (17 (dup)) 
                                      (18 (invokespecial (methodCP "<init>" "java.lang.AssertionError" () void))) 
                                      (21 (athrow)) 
                                      (22 (aload_0)) ;;at TAG_0
                                      (23 (aload_1)) 
                                      (24 (putfield (fieldCP "cmp" "java.util.Collections$ReverseComparator2" (class "java.util.Comparator")))) 
                                      (27 (return)) 
                                      (endofcode 28))
                                   (Exceptions )
                                   (StackMap )))
                        (method "compare"
                              (parameters (class "java.lang.Object") (class "java.lang.Object"))
                              (returntype . int)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 3) (max_locals . 3) (code_length . 12)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "cmp" "java.util.Collections$ReverseComparator2" (class "java.util.Comparator"))))
                                      (4 (aload_2))
                                      (5 (aload_1))
                                      (6 (invokeinterface
					(methodCP "compare" "java.util.Comparator" ((class "java.lang.Object") (class "java.lang.Object")) int) 3))
                                      (11 (ireturn))
                                      (endofcode 12))
                                   (Exceptions )
                                   (StackMap )))
                        (method "equals"
                              (parameters (class "java.lang.Object"))
                              (returntype . boolean)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 2) (code_length . 37)
                                   (parsedcode
                                      (0 (aload_1)) 
                                      (1 (aload_0)) 
                                      (2 (if_acmpeq 31)) ;;to TAG_0
                                      (5 (aload_1)) 
                                      (6 (instanceof (class "java.util.Collections$ReverseComparator2"))) 
                                      (9 (ifeq 35)) ;;to TAG_1
                                      (12 (aload_0)) 
                                      (13 (getfield (fieldCP "cmp" "java.util.Collections$ReverseComparator2" (class "java.util.Comparator")))) 
                                      (16 (aload_1)) 
                                      (17 (checkcast (class "java.util.Collections$ReverseComparator2"))) 
                                      (20 (getfield (fieldCP "cmp" "java.util.Collections$ReverseComparator2" (class "java.util.Comparator")))) 
                                      (23 (invokeinterface (methodCP "equals" "java.util.Comparator" ((class "java.lang.Object")) boolean) 2)) 
                                      (28 (ifeq 35)) ;;to TAG_1
                                      (31 (iconst_1)) ;;at TAG_0
                                      (32 (goto 36))  ;;to TAG_2
                                      (35 (iconst_0)) ;;at TAG_1
                                      (36 (ireturn)) ;;at TAG_2
                                      (endofcode 37))
                                   (Exceptions )
                                   (StackMap )))
                        (method "hashCode"
                              (parameters )
                              (returntype . int)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 11)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "cmp" "java.util.Collections$ReverseComparator2" (class "java.util.Comparator"))))
                                      (4 (invokevirtual
					(methodCP "hashCode" "java.lang.Object" () int)))
                                      (7 (ldc 1))         ;;INT:: "-2147483648"
                                      (9 (ixor))
                                      (10 (ireturn))
                                      (endofcode 11))
                                   (Exceptions )
                                   (StackMap )))
                        (method "<clinit>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *static* )
                              (code
                                   (max_stack . 1) (max_locals . 0) (code_length . 18)
                                   (parsedcode
                                      (0 (ldc_w )) 
                                      (3 (invokevirtual (methodCP "desiredAssertionStatus" "java.lang.Class" () boolean))) 
                                      (6 (ifne 13))  ;;to TAG_0
                                      (9 (iconst_1)) 
                                      (10 (goto 14)) ;;to TAG_1
                                      (13 (iconst_0)) ;;at TAG_0
                                      (14 (putstatic (fieldCP "$assertionsDisabled" "java.util.Collections$ReverseComparator2" boolean))) ;;at TAG_1
                                      (17 (return)) 
                                      (endofcode 18))
                                   (Exceptions )
                                   (StackMap ))))
            (interfaces "java.util.Comparator" "java.io.Serializable")
            (accessflags  *class*  *super*  *synchronized* )
            (attributes
              (attribute "SourceFile")
              (attribute "Signature")
              (attribute "InnerClasses")))))


(defconst *Collections$ReverseComparator2-class-table*
  (make-static-class-decls 
   *java.util.Collections$ReverseComparator2*))

(defconst *package-name-map* 
  ("java.util.Collections$ReverseComparator2" . "java.util"))

