; LinkedHashMap-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:39:46 CDT 2014.
;

(defconst *java.util.LinkedHashMap*
 (make-class-def
      '(class "java.util.LinkedHashMap"
            "java.util.HashMap"
            (constant_pool
                        (LONG 3801124242820219131))
            (fields
                        (field "serialVersionUID" long (accessflags  *class*  *final*  *private*  *static* ) 0)
                        (field "header" (class "java.util.LinkedHashMap$Entry") (accessflags  *class*  *private*  *transient* ) -1)
                        (field "accessOrder" boolean (accessflags  *class*  *final*  *private* ) -1))
            (methods
                        (method "<init>"
                              (parameters int float)
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 3) (max_locals . 3) (code_length . 12)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (iload_1))
                                      (2 (fload_2))
                                      (3 (invokespecial
					(methodCP "<init>" "java.util.HashMap" (int float) void)))
                                      (6 (aload_0))
                                      (7 (iconst_0))
                                      (8 (putfield (fieldCP "accessOrder" "java.util.LinkedHashMap" boolean)))
                                      (11 (return))
                                      (endofcode 12))
                                   (Exceptions )
                                   (StackMap )))
                        (method "<init>"
                              (parameters int)
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 2) (code_length . 11)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (iload_1))
                                      (2 (invokespecial
					(methodCP "<init>" "java.util.HashMap" (int) void)))
                                      (5 (aload_0))
                                      (6 (iconst_0))
                                      (7 (putfield (fieldCP "accessOrder" "java.util.LinkedHashMap" boolean)))
                                      (10 (return))
                                      (endofcode 11))
                                   (Exceptions )
                                   (StackMap )))
                        (method "<init>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 10)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (invokespecial
					(methodCP "<init>" "java.util.HashMap" () void)))
                                      (4 (aload_0))
                                      (5 (iconst_0))
                                      (6 (putfield (fieldCP "accessOrder" "java.util.LinkedHashMap" boolean)))
                                      (9 (return))
                                      (endofcode 10))
                                   (Exceptions )
                                   (StackMap )))
                        (method "<init>"
                              (parameters (class "java.util.Map"))
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 2) (code_length . 11)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (invokespecial
					(methodCP "<init>" "java.util.HashMap" ((class "java.util.Map")) void)))
                                      (5 (aload_0))
                                      (6 (iconst_0))
                                      (7 (putfield (fieldCP "accessOrder" "java.util.LinkedHashMap" boolean)))
                                      (10 (return))
                                      (endofcode 11))
                                   (Exceptions )
                                   (StackMap )))
                        (method "<init>"
                              (parameters int float boolean)
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 3) (max_locals . 4) (code_length . 12)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (iload_1))
                                      (2 (fload_2))
                                      (3 (invokespecial
					(methodCP "<init>" "java.util.HashMap" (int float) void)))
                                      (6 (aload_0))
                                      (7 (iload_3))
                                      (8 (putfield (fieldCP "accessOrder" "java.util.LinkedHashMap" boolean)))
                                      (11 (return))
                                      (endofcode 12))
                                   (Exceptions )
                                   (StackMap )))
                        (method "init"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class* )
                              (code
                                   (max_stack . 7) (max_locals . 1) (code_length . 35)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (new (class "java.util.LinkedHashMap$Entry")))
                                      (4 (dup))
                                      (5 (iconst_m1))
                                      (6 (aconst_null))
                                      (7 (aconst_null))
                                      (8 (aconst_null))
                                      (9 (invokespecial
					(methodCP "<init>" "java.util.LinkedHashMap$Entry" (int (class "java.lang.Object") (class "java.lang.Object") (class "java.util.HashMap$Entry")) void)))
                                      (12 (putfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry"))))
                                      (15 (aload_0))
                                      (16 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry"))))
                                      (19 (aload_0))
                                      (20 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry"))))
                                      (23 (aload_0))
                                      (24 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry"))))
                                      (27 (dup_x1))
                                      (28 (putfield (fieldCP "after" "java.util.LinkedHashMap$Entry" (class "java.util.LinkedHashMap$Entry"))))
                                      (31 (putfield (fieldCP "before" "java.util.LinkedHashMap$Entry" (class "java.util.LinkedHashMap$Entry"))))
                                      (34 (return))
                                      (endofcode 35))
                                   (Exceptions )
                                   (StackMap )))
                        (method "transfer"
                              (parameters (array (class "java.util.HashMap$Entry")))
                              (returntype . void)
                              (accessflags  *class* )
                              (code
                                   (max_stack . 3) (max_locals . 5) (code_length . 51)
                                   (parsedcode
                                      (0 (aload_1)) 
                                      (1 (arraylength)) 
                                      (2 (istore_2)) 
                                      (3 (aload_0)) 
                                      (4 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry")))) 
                                      (7 (getfield (fieldCP "after" "java.util.LinkedHashMap$Entry" (class "java.util.LinkedHashMap$Entry")))) 
                                      (10 (astore_3)) 
                                      (11 (aload_3)) ;;at TAG_1
                                      (12 (aload_0)) 
                                      (13 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry")))) 
                                      (16 (if_acmpeq 50))  ;;to TAG_0
                                      (19 (aload_3)) 
                                      (20 (getfield (fieldCP "hash" "java.util.LinkedHashMap$Entry" int))) 
                                      (23 (iload_2)) 
                                      (24 (invokestatic (methodCP "indexFor" "java.util.LinkedHashMap" (int int) int))) 
                                      (27 (istore 4)) 
                                      (29 (aload_3)) 
                                      (30 (aload_1)) 
                                      (31 (iload 4)) 
                                      (33 (aaload)) 
                                      (34 (putfield (fieldCP "next" "java.util.LinkedHashMap$Entry" (class "java.util.HashMap$Entry")))) 
                                      (37 (aload_1)) 
                                      (38 (iload 4)) 
                                      (40 (aload_3)) 
                                      (41 (aastore)) 
                                      (42 (aload_3)) 
                                      (43 (getfield (fieldCP "after" "java.util.LinkedHashMap$Entry" (class "java.util.LinkedHashMap$Entry")))) 
                                      (46 (astore_3)) 
                                      (47 (goto 11)) ;;to TAG_1
                                      (50 (return)) ;;at TAG_0
                                      (endofcode 51))
                                   (Exceptions )
                                   (StackMap )))
                        (method "containsValue"
                              (parameters (class "java.lang.Object"))
                              (returntype . boolean)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 3) (code_length . 79)
                                   (parsedcode
                                      (0 (aload_1)) 
                                      (1 (ifnonnull 40)) ;;to TAG_0
                                      (4 (aload_0)) 
                                      (5 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry")))) 
                                      (8 (getfield (fieldCP "after" "java.util.LinkedHashMap$Entry" (class "java.util.LinkedHashMap$Entry")))) 
                                      (11 (astore_2)) 
                                      (12 (aload_2)) ;;at TAG_3
                                      (13 (aload_0)) 
                                      (14 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry")))) 
                                      (17 (if_acmpeq 37)) ;;to TAG_1
                                      (20 (aload_2)) 
                                      (21 (getfield (fieldCP "value" "java.util.LinkedHashMap$Entry" (class "java.lang.Object")))) 
                                      (24 (ifnonnull 29))  ;;to TAG_2
                                      (27 (iconst_1)) 
                                      (28 (ireturn)) 
                                      (29 (aload_2)) ;;at TAG_2
                                      (30 (getfield (fieldCP "after" "java.util.LinkedHashMap$Entry" (class "java.util.LinkedHashMap$Entry")))) 
                                      (33 (astore_2)) 
                                      (34 (goto 12)) ;;to TAG_3
                                      (37 (goto 77)) ;;to TAG_4;;at TAG_1
                                      (40 (aload_0)) ;;at TAG_0
                                      (41 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry")))) 
                                      (44 (getfield (fieldCP "after" "java.util.LinkedHashMap$Entry" (class "java.util.LinkedHashMap$Entry")))) 
                                      (47 (astore_2)) 
                                      (48 (aload_2)) ;;at TAG_6
                                      (49 (aload_0)) 
                                      (50 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry")))) 
                                      (53 (if_acmpeq 77)) ;;to TAG_4
                                      (56 (aload_1)) 
                                      (57 (aload_2)) 
                                      (58 (getfield (fieldCP "value" "java.util.LinkedHashMap$Entry" (class "java.lang.Object")))) 
                                      (61 (invokevirtual (methodCP "equals" "java.lang.Object" ((class "java.lang.Object")) boolean))) 
                                      (64 (ifeq 69)) ;;to TAG_5
                                      (67 (iconst_1)) 
                                      (68 (ireturn)) 
                                      (69 (aload_2)) ;;at TAG_5
                                      (70 (getfield (fieldCP "after" "java.util.LinkedHashMap$Entry" (class "java.util.LinkedHashMap$Entry")))) 
                                      (73 (astore_2)) 
                                      (74 (goto 48)) ;;to TAG_6
                                      (77 (iconst_0)) ;;at TAG_4
                                      (78 (ireturn)) 
                                      (endofcode 79))
                                   (Exceptions )
                                   (StackMap )))
                        (method "get"
                              (parameters (class "java.lang.Object"))
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 3) (code_length . 25)
                                   (parsedcode
                                      (0 (aload_0)) 
                                      (1 (aload_1)) 
                                      (2 (invokevirtual (methodCP "getEntry" "java.util.LinkedHashMap" ((class "java.lang.Object")) (class "java.util.HashMap$Entry")))) 
                                      (5 (checkcast (class "java.util.LinkedHashMap$Entry"))) 
                                      (8 (astore_2)) 
                                      (9 (aload_2)) 
                                      (10 (ifnonnull 15))  ;;to TAG_0
                                      (13 (aconst_null)) 
                                      (14 (areturn)) 
                                      (15 (aload_2)) ;;at TAG_0
                                      (16 (aload_0)) 
                                      (17 (invokevirtual (methodCP "recordAccess" "java.util.LinkedHashMap$Entry" ((class "java.util.HashMap")) void))) 
                                      (20 (aload_2)) 
                                      (21 (getfield (fieldCP "value" "java.util.LinkedHashMap$Entry" (class "java.lang.Object")))) 
                                      (24 (areturn)) 
                                      (endofcode 25))
                                   (Exceptions )
                                   (StackMap )))
                        (method "clear"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 4) (max_locals . 1) (code_length . 24)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (invokespecial
					(methodCP "clear" "java.util.HashMap" () void)))
                                      (4 (aload_0))
                                      (5 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry"))))
                                      (8 (aload_0))
                                      (9 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry"))))
                                      (12 (aload_0))
                                      (13 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry"))))
                                      (16 (dup_x1))
                                      (17 (putfield (fieldCP "after" "java.util.LinkedHashMap$Entry" (class "java.util.LinkedHashMap$Entry"))))
                                      (20 (putfield (fieldCP "before" "java.util.LinkedHashMap$Entry" (class "java.util.LinkedHashMap$Entry"))))
                                      (23 (return))
                                      (endofcode 24))
                                   (Exceptions )
                                   (StackMap )))
                        (method "newKeyIterator"
                              (parameters )
                              (returntype . (class "java.util.Iterator"))
                              (accessflags  *class* )
                              (code
                                   (max_stack . 4) (max_locals . 1) (code_length . 10)
                                   (parsedcode
                                      (0 (new (class "java.util.LinkedHashMap$KeyIterator")))
                                      (3 (dup))
                                      (4 (aload_0))
                                      (5 (aconst_null))
                                      (6 (invokespecial
					(methodCP "<init>" "java.util.LinkedHashMap$KeyIterator" ((class "java.util.LinkedHashMap") (class "java.util.LinkedHashMap$1")) void)))
                                      (9 (areturn))
                                      (endofcode 10))
                                   (Exceptions )
                                   (StackMap )))
                        (method "newValueIterator"
                              (parameters )
                              (returntype . (class "java.util.Iterator"))
                              (accessflags  *class* )
                              (code
                                   (max_stack . 4) (max_locals . 1) (code_length . 10)
                                   (parsedcode
                                      (0 (new (class "java.util.LinkedHashMap$ValueIterator")))
                                      (3 (dup))
                                      (4 (aload_0))
                                      (5 (aconst_null))
                                      (6 (invokespecial
					(methodCP "<init>" "java.util.LinkedHashMap$ValueIterator" ((class "java.util.LinkedHashMap") (class "java.util.LinkedHashMap$1")) void)))
                                      (9 (areturn))
                                      (endofcode 10))
                                   (Exceptions )
                                   (StackMap )))
                        (method "newEntryIterator"
                              (parameters )
                              (returntype . (class "java.util.Iterator"))
                              (accessflags  *class* )
                              (code
                                   (max_stack . 4) (max_locals . 1) (code_length . 10)
                                   (parsedcode
                                      (0 (new (class "java.util.LinkedHashMap$EntryIterator")))
                                      (3 (dup))
                                      (4 (aload_0))
                                      (5 (aconst_null))
                                      (6 (invokespecial
					(methodCP "<init>" "java.util.LinkedHashMap$EntryIterator" ((class "java.util.LinkedHashMap") (class "java.util.LinkedHashMap$1")) void)))
                                      (9 (areturn))
                                      (endofcode 10))
                                   (Exceptions )
                                   (StackMap )))
                        (method "addEntry"
                              (parameters int (class "java.lang.Object") (class "java.lang.Object") int)
                              (returntype . void)
                              (accessflags  *class* )
                              (code
                                   (max_stack . 5) (max_locals . 6) (code_length . 63)
                                   (parsedcode
                                      (0 (aload_0)) 
                                      (1 (iload_1)) 
                                      (2 (aload_2)) 
                                      (3 (aload_3)) 
                                      (4 (iload 4)) 
                                      (6 (invokevirtual (methodCP "createEntry" "java.util.LinkedHashMap" (int (class "java.lang.Object") (class "java.lang.Object") int) void))) 
                                      (9 (aload_0)) 
                                      (10 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry")))) 
                                      (13 (getfield (fieldCP "after" "java.util.LinkedHashMap$Entry" (class "java.util.LinkedHashMap$Entry")))) 
                                      (16 (astore 5)) 
                                      (18 (aload_0)) 
                                      (19 (aload 5)) 
                                      (21 (invokevirtual (methodCP "removeEldestEntry" "java.util.LinkedHashMap" ((class "java.util.Map$Entry")) boolean))) 
                                      (24 (ifeq 40))  ;;to TAG_0
                                      (27 (aload_0)) 
                                      (28 (aload 5)) 
                                      (30 (getfield (fieldCP "key" "java.util.LinkedHashMap$Entry" (class "java.lang.Object")))) 
                                      (33 (invokevirtual (methodCP "removeEntryForKey" "java.util.LinkedHashMap" ((class "java.lang.Object")) (class "java.util.HashMap$Entry")))) 
                                      (36 (pop)) 
                                      (37 (goto 62)) ;;to TAG_1
                                      (40 (aload_0)) ;;at TAG_0
                                      (41 (getfield (fieldCP "size" "java.util.LinkedHashMap" int))) 
                                      (44 (aload_0)) 
                                      (45 (getfield (fieldCP "threshold" "java.util.LinkedHashMap" int))) 
                                      (48 (if_icmplt 62)) ;;to TAG_1
                                      (51 (aload_0)) 
                                      (52 (iconst_2)) 
                                      (53 (aload_0)) 
                                      (54 (getfield (fieldCP "table" "java.util.LinkedHashMap" (array (class "java.util.HashMap$Entry"))))) 
                                      (57 (arraylength)) 
                                      (58 (imul)) 
                                      (59 (invokevirtual (methodCP "resize" "java.util.LinkedHashMap" (int) void))) 
                                      (62 (return)) ;;at TAG_1
                                      (endofcode 63))
                                   (Exceptions )
                                   (StackMap )))
                        (method "createEntry"
                              (parameters int (class "java.lang.Object") (class "java.lang.Object") int)
                              (returntype . void)
                              (accessflags  *class* )
                              (code
                                   (max_stack . 6) (max_locals . 7) (code_length . 52)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "table" "java.util.LinkedHashMap" (array (class "java.util.HashMap$Entry")))))
                                      (4 (iload 4))
                                      (6 (aaload))
                                      (7 (astore 5))
                                      (9 (new (class "java.util.LinkedHashMap$Entry")))
                                      (12 (dup))
                                      (13 (iload_1))
                                      (14 (aload_2))
                                      (15 (aload_3))
                                      (16 (aload 5))
                                      (18 (invokespecial
					(methodCP "<init>" "java.util.LinkedHashMap$Entry" (int (class "java.lang.Object") (class "java.lang.Object") (class "java.util.HashMap$Entry")) void)))
                                      (21 (astore 6))
                                      (23 (aload_0))
                                      (24 (getfield (fieldCP "table" "java.util.LinkedHashMap" (array (class "java.util.HashMap$Entry")))))
                                      (27 (iload 4))
                                      (29 (aload 6))
                                      (31 (aastore))
                                      (32 (aload 6))
                                      (34 (aload_0))
                                      (35 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry"))))
                                      (38 (invokestatic
					(methodCP "access$600" "java.util.LinkedHashMap$Entry" ((class "java.util.LinkedHashMap$Entry") (class "java.util.LinkedHashMap$Entry")) void)))
                                      (41 (aload_0))
                                      (42 (dup))
                                      (43 (getfield (fieldCP "size" "java.util.LinkedHashMap" int)))
                                      (46 (iconst_1))
                                      (47 (iadd))
                                      (48 (putfield (fieldCP "size" "java.util.LinkedHashMap" int)))
                                      (51 (return))
                                      (endofcode 52))
                                   (Exceptions )
                                   (StackMap )))
                        (method "removeEldestEntry"
                              (parameters (class "java.util.Map$Entry"))
                              (returntype . boolean)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 1) (max_locals . 2) (code_length . 2)
                                   (parsedcode
                                      (0 (iconst_0))
                                      (1 (ireturn))
                                      (endofcode 2))
                                   (Exceptions )
                                   (StackMap )))
                        (method "access$000"
                              (parameters (class "java.util.LinkedHashMap"))
                              (returntype . boolean)
                              (accessflags  *class*  *static* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "accessOrder" "java.util.LinkedHashMap" boolean)))
                                      (4 (ireturn))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "access$100"
                              (parameters (class "java.util.LinkedHashMap"))
                              (returntype . (class "java.util.LinkedHashMap$Entry"))
                              (accessflags  *class*  *static* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "header" "java.util.LinkedHashMap" (class "java.util.LinkedHashMap$Entry"))))
                                      (4 (areturn))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap ))))
            (interfaces "java.util.Map")
            (accessflags  *class*  *public*  *super*  *synchronized* )
            (attributes
              (attribute "SourceFile")
              (attribute "Signature")
              (attribute "InnerClasses")))))


(defconst *LinkedHashMap-class-table*
  (make-static-class-decls 
   *java.util.LinkedHashMap*))

(defconst *package-name-map* 
  ("java.util.LinkedHashMap" . "java.util"))

