; ToGeneric$A8-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:39:35 CDT 2014.
;

(defconst *java.lang.invoke.ToGeneric$A8*
 (make-class-def
      '(class "java.lang.invoke.ToGeneric$A8"
            "java.lang.invoke.ToGeneric$Adapter"
            (constant_pool)
            (fields)
            (methods
                        (method "<init>"
                              (parameters (class "java.lang.invoke.MethodHandle"))
                              (returntype . void)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 2) (max_locals . 2) (code_length . 6)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (invokespecial
					(methodCP "<init>" "java.lang.invoke.ToGeneric$Adapter" ((class "java.lang.invoke.MethodHandle")) void)))
                                      (5 (return))
                                      (endofcode 6))
                                   (Exceptions )
                                   (StackMap )))
                        (method "<init>"
                              (parameters (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle"))
                              (returntype . void)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 5) (max_locals . 5) (code_length . 10)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (aload_2))
                                      (3 (aload_3))
                                      (4 (aload 4))
                                      (6 (invokespecial
					(methodCP "<init>" "java.lang.invoke.ToGeneric$Adapter" ((class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle")) void)))
                                      (9 (return))
                                      (endofcode 10))
                                   (Exceptions )
                                   (StackMap )))
                        (method "makeInstance"
                              (parameters (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle"))
                              (returntype . (class "java.lang.invoke.ToGeneric$A8"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 6) (max_locals . 5) (code_length . 13)
                                   (parsedcode
                                      (0 (new (class "java.lang.invoke.ToGeneric$A8")))
                                      (3 (dup))
                                      (4 (aload_1))
                                      (5 (aload_2))
                                      (6 (aload_3))
                                      (7 (aload 4))
                                      (9 (invokespecial
					(methodCP "<init>" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle")) void)))
                                      (12 (areturn))
                                      (endofcode 13))
                                   (Exceptions )
                                   (StackMap )))
                        (method "target"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object"))
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 9) (code_length . 25)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "invoker" "java.lang.invoke.ToGeneric$A8" (class "java.lang.invoke.MethodHandle"))))
                                      (4 (aload_0))
                                      (5 (getfield (fieldCP "target" "java.lang.invoke.ToGeneric$A8" (class "java.lang.invoke.MethodHandle"))))
                                      (8 (aload_1))
                                      (9 (aload_2))
                                      (10 (aload_3))
                                      (11 (aload 4))
                                      (13 (aload 5))
                                      (15 (aload 6))
                                      (17 (aload 7))
                                      (19 (aload 8))
                                      (21 (invokevirtual
					(methodCP "invokeExact" "java.lang.invoke.MethodHandle" ((class "java.lang.invoke.MethodHandle") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (24 (areturn))
                                      (endofcode 25))
                                   (Exceptions )
                                   (StackMap )))
                        (method "targetA8"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object"))
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 9) (max_locals . 9) (code_length . 18)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (aload_2))
                                      (3 (aload_3))
                                      (4 (aload 4))
                                      (6 (aload 5))
                                      (8 (aload 6))
                                      (10 (aload 7))
                                      (12 (aload 8))
                                      (14 (invokevirtual
					(methodCP "target" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (17 (areturn))
                                      (endofcode 18))
                                   (Exceptions )
                                   (StackMap )))
                        (method "targetA8"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 10) (code_length . 21)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (aload_2))
                                      (3 (aload_3))
                                      (4 (aload 4))
                                      (6 (aload 5))
                                      (8 (aload 6))
                                      (10 (aload 7))
                                      (12 (lload 8))
                                      (14 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (17 (invokevirtual
					(methodCP "target" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (20 (areturn))
                                      (endofcode 21))
                                   (Exceptions )
                                   (StackMap )))
                        (method "targetA8"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 11) (code_length . 24)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (aload_2))
                                      (3 (aload_3))
                                      (4 (aload 4))
                                      (6 (aload 5))
                                      (8 (aload 6))
                                      (10 (lload 7))
                                      (12 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (15 (lload 9))
                                      (17 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (20 (invokevirtual
					(methodCP "target" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (23 (areturn))
                                      (endofcode 24))
                                   (Exceptions )
                                   (StackMap )))
                        (method "targetA8"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 12) (code_length . 27)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (aload_2))
                                      (3 (aload_3))
                                      (4 (aload 4))
                                      (6 (aload 5))
                                      (8 (lload 6))
                                      (10 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (13 (lload 8))
                                      (15 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (18 (lload 10))
                                      (20 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (23 (invokevirtual
					(methodCP "target" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (26 (areturn))
                                      (endofcode 27))
                                   (Exceptions )
                                   (StackMap )))
                        (method "targetA8"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 13) (code_length . 30)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (aload_2))
                                      (3 (aload_3))
                                      (4 (aload 4))
                                      (6 (lload 5))
                                      (8 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (11 (lload 7))
                                      (13 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (16 (lload 9))
                                      (18 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (21 (lload 11))
                                      (23 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (26 (invokevirtual
					(methodCP "target" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (29 (areturn))
                                      (endofcode 30))
                                   (Exceptions )
                                   (StackMap )))
                        (method "targetA8"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 14) (code_length . 33)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (aload_2))
                                      (3 (aload_3))
                                      (4 (lload 4))
                                      (6 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (9 (lload 6))
                                      (11 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (14 (lload 8))
                                      (16 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (19 (lload 10))
                                      (21 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (24 (lload 12))
                                      (26 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (29 (invokevirtual
					(methodCP "target" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (32 (areturn))
                                      (endofcode 33))
                                   (Exceptions )
                                   (StackMap )))
                        (method "targetA8"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") long long long long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 15) (code_length . 36)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (aload_2))
                                      (3 (lload_3))
                                      (4 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (7 (lload 5))
                                      (9 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (12 (lload 7))
                                      (14 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (17 (lload 9))
                                      (19 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (22 (lload 11))
                                      (24 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (27 (lload 13))
                                      (29 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (32 (invokevirtual
					(methodCP "target" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (35 (areturn))
                                      (endofcode 36))
                                   (Exceptions )
                                   (StackMap )))
                        (method "targetA8"
                              (parameters (class "java.lang.Object") long long long long long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 16) (code_length . 40)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (lload_2))
                                      (3 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (6 (lload 4))
                                      (8 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (11 (lload 6))
                                      (13 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (16 (lload 8))
                                      (18 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (21 (lload 10))
                                      (23 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (26 (lload 12))
                                      (28 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (31 (lload 14))
                                      (33 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (36 (invokevirtual
					(methodCP "target" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (39 (areturn))
                                      (endofcode 40))
                                   (Exceptions )
                                   (StackMap )))
                        (method "targetA8"
                              (parameters long long long long long long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 17) (code_length . 43)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (lload_1))
                                      (2 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (5 (lload_3))
                                      (6 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (9 (lload 5))
                                      (11 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (14 (lload 7))
                                      (16 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (19 (lload 9))
                                      (21 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (24 (lload 11))
                                      (26 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (29 (lload 13))
                                      (31 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (34 (lload 15))
                                      (36 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (39 (invokevirtual
					(methodCP "target" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (42 (areturn))
                                      (endofcode 43))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_L"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object"))
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 9) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (aload 6))
                                      (11 (aload 7))
                                      (13 (aload 8))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_L" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) (class "java.lang.Object"))))
                                      (21 (areturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_I"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object"))
                              (returntype . int)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 9) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (aload 6))
                                      (11 (aload 7))
                                      (13 (aload 8))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_I" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) int)))
                                      (21 (ireturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_J"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object"))
                              (returntype . long)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 10) (max_locals . 9) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (aload 6))
                                      (11 (aload 7))
                                      (13 (aload 8))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_J" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) long)))
                                      (21 (lreturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_L"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 11) (max_locals . 10) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (aload 6))
                                      (11 (aload 7))
                                      (13 (lload 8))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_L" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) (class "java.lang.Object"))))
                                      (21 (areturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_I"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long)
                              (returntype . int)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 11) (max_locals . 10) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (aload 6))
                                      (11 (aload 7))
                                      (13 (lload 8))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_I" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) int)))
                                      (21 (ireturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_J"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long)
                              (returntype . long)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 11) (max_locals . 10) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (aload 6))
                                      (11 (aload 7))
                                      (13 (lload 8))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_J" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) long)))
                                      (21 (lreturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_L"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 12) (max_locals . 11) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (aload 6))
                                      (11 (lload 7))
                                      (13 (lload 9))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_L" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) (class "java.lang.Object"))))
                                      (21 (areturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_I"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long)
                              (returntype . int)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 12) (max_locals . 11) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (aload 6))
                                      (11 (lload 7))
                                      (13 (lload 9))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_I" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) int)))
                                      (21 (ireturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_J"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long)
                              (returntype . long)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 12) (max_locals . 11) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (aload 6))
                                      (11 (lload 7))
                                      (13 (lload 9))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_J" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) long)))
                                      (21 (lreturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_L"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 13) (max_locals . 12) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (lload 6))
                                      (11 (lload 8))
                                      (13 (lload 10))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_L" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) (class "java.lang.Object"))))
                                      (21 (areturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_I"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long)
                              (returntype . int)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 13) (max_locals . 12) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (lload 6))
                                      (11 (lload 8))
                                      (13 (lload 10))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_I" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) int)))
                                      (21 (ireturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_J"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long)
                              (returntype . long)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 13) (max_locals . 12) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (aload 5))
                                      (9 (lload 6))
                                      (11 (lload 8))
                                      (13 (lload 10))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_J" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) long)))
                                      (21 (lreturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_L"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 14) (max_locals . 13) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (lload 5))
                                      (9 (lload 7))
                                      (11 (lload 9))
                                      (13 (lload 11))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_L" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) (class "java.lang.Object"))))
                                      (21 (areturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_I"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long)
                              (returntype . int)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 14) (max_locals . 13) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (lload 5))
                                      (9 (lload 7))
                                      (11 (lload 9))
                                      (13 (lload 11))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_I" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) int)))
                                      (21 (ireturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_J"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long)
                              (returntype . long)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 14) (max_locals . 13) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (aload 4))
                                      (7 (lload 5))
                                      (9 (lload 7))
                                      (11 (lload 9))
                                      (13 (lload 11))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_J" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) long)))
                                      (21 (lreturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_L"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 15) (max_locals . 14) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (lload 4))
                                      (7 (lload 6))
                                      (9 (lload 8))
                                      (11 (lload 10))
                                      (13 (lload 12))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_L" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) (class "java.lang.Object"))))
                                      (21 (areturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_I"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long long)
                              (returntype . int)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 15) (max_locals . 14) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (lload 4))
                                      (7 (lload 6))
                                      (9 (lload 8))
                                      (11 (lload 10))
                                      (13 (lload 12))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_I" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) int)))
                                      (21 (ireturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_J"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long long)
                              (returntype . long)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 15) (max_locals . 14) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (aload_3))
                                      (5 (lload 4))
                                      (7 (lload 6))
                                      (9 (lload 8))
                                      (11 (lload 10))
                                      (13 (lload 12))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") long long long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_J" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) long)))
                                      (21 (lreturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_L"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") long long long long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 16) (max_locals . 15) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (lload_3))
                                      (5 (lload 5))
                                      (7 (lload 7))
                                      (9 (lload 9))
                                      (11 (lload 11))
                                      (13 (lload 13))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") long long long long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_L" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) (class "java.lang.Object"))))
                                      (21 (areturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_I"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") long long long long long long)
                              (returntype . int)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 16) (max_locals . 15) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (lload_3))
                                      (5 (lload 5))
                                      (7 (lload 7))
                                      (9 (lload 9))
                                      (11 (lload 11))
                                      (13 (lload 13))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") long long long long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_I" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) int)))
                                      (21 (ireturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_J"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") long long long long long long)
                              (returntype . long)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 16) (max_locals . 15) (code_length . 22)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (aload_2))
                                      (4 (lload_3))
                                      (5 (lload 5))
                                      (7 (lload 7))
                                      (9 (lload 9))
                                      (11 (lload 11))
                                      (13 (lload 13))
                                      (15 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") (class "java.lang.Object") long long long long long long) (class "java.lang.Object"))))
                                      (18 (invokevirtual
					(methodCP "return_J" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) long)))
                                      (21 (lreturn))
                                      (endofcode 22))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_L"
                              (parameters (class "java.lang.Object") long long long long long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 17) (max_locals . 16) (code_length . 23)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (lload_2))
                                      (4 (lload 4))
                                      (6 (lload 6))
                                      (8 (lload 8))
                                      (10 (lload 10))
                                      (12 (lload 12))
                                      (14 (lload 14))
                                      (16 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") long long long long long long long) (class "java.lang.Object"))))
                                      (19 (invokevirtual
					(methodCP "return_L" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) (class "java.lang.Object"))))
                                      (22 (areturn))
                                      (endofcode 23))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_I"
                              (parameters (class "java.lang.Object") long long long long long long long)
                              (returntype . int)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 17) (max_locals . 16) (code_length . 23)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (lload_2))
                                      (4 (lload 4))
                                      (6 (lload 6))
                                      (8 (lload 8))
                                      (10 (lload 10))
                                      (12 (lload 12))
                                      (14 (lload 14))
                                      (16 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") long long long long long long long) (class "java.lang.Object"))))
                                      (19 (invokevirtual
					(methodCP "return_I" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) int)))
                                      (22 (ireturn))
                                      (endofcode 23))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_J"
                              (parameters (class "java.lang.Object") long long long long long long long)
                              (returntype . long)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 17) (max_locals . 16) (code_length . 23)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (aload_1))
                                      (3 (lload_2))
                                      (4 (lload 4))
                                      (6 (lload 6))
                                      (8 (lload 8))
                                      (10 (lload 10))
                                      (12 (lload 12))
                                      (14 (lload 14))
                                      (16 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object") long long long long long long long) (class "java.lang.Object"))))
                                      (19 (invokevirtual
					(methodCP "return_J" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) long)))
                                      (22 (lreturn))
                                      (endofcode 23))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_L"
                              (parameters long long long long long long long long)
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 18) (max_locals . 17) (code_length . 23)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (lload_1))
                                      (3 (lload_3))
                                      (4 (lload 5))
                                      (6 (lload 7))
                                      (8 (lload 9))
                                      (10 (lload 11))
                                      (12 (lload 13))
                                      (14 (lload 15))
                                      (16 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" (long long long long long long long long) (class "java.lang.Object"))))
                                      (19 (invokevirtual
					(methodCP "return_L" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) (class "java.lang.Object"))))
                                      (22 (areturn))
                                      (endofcode 23))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_I"
                              (parameters long long long long long long long long)
                              (returntype . int)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 18) (max_locals . 17) (code_length . 23)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (lload_1))
                                      (3 (lload_3))
                                      (4 (lload 5))
                                      (6 (lload 7))
                                      (8 (lload 9))
                                      (10 (lload 11))
                                      (12 (lload 13))
                                      (14 (lload 15))
                                      (16 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" (long long long long long long long long) (class "java.lang.Object"))))
                                      (19 (invokevirtual
					(methodCP "return_I" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) int)))
                                      (22 (ireturn))
                                      (endofcode 23))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke_J"
                              (parameters long long long long long long long long)
                              (returntype . long)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 18) (max_locals . 17) (code_length . 23)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_0))
                                      (2 (lload_1))
                                      (3 (lload_3))
                                      (4 (lload 5))
                                      (6 (lload 7))
                                      (8 (lload 9))
                                      (10 (lload 11))
                                      (12 (lload 13))
                                      (14 (lload 15))
                                      (16 (invokevirtual
					(methodCP "targetA8" "java.lang.invoke.ToGeneric$A8" (long long long long long long long long) (class "java.lang.Object"))))
                                      (19 (invokevirtual
					(methodCP "return_J" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.Object")) long)))
                                      (22 (lreturn))
                                      (endofcode 23))
                                   (Exceptions )
                                   (StackMap )))
                        (method "makeInstance"
                              (parameters (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle"))
                              (returntype . (class "java.lang.invoke.ToGeneric$Adapter"))
                              (accessflags  *class*  *protected*  *volatile* )
                              (code
                                   (max_stack . 5) (max_locals . 5) (code_length . 10)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (aload_2))
                                      (3 (aload_3))
                                      (4 (aload 4))
                                      (6 (invokevirtual
					(methodCP "makeInstance" "java.lang.invoke.ToGeneric$A8" ((class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle") (class "java.lang.invoke.MethodHandle")) (class "java.lang.invoke.ToGeneric$A8"))))
                                      (9 (areturn))
                                      (endofcode 10))
                                   (Exceptions )
                                   (StackMap ))))
            (interfaces)
            (accessflags  *class*  *super*  *synchronized* )
            (attributes
              (attribute "SourceFile")
              (attribute "InnerClasses")))))


(defconst *ToGeneric$A8-class-table*
  (make-static-class-decls 
   *java.lang.invoke.ToGeneric$A8*))

(defconst *package-name-map* 
  ("java.lang.invoke.ToGeneric$A8" . "java.lang.invoke"))

