; KeyEventDispatcher-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:39:29 CDT 2014.
;

(defconst *java.awt.KeyEventDispatcher*
 (make-class-def
      '(class "java.awt.KeyEventDispatcher"
            "java.lang.Object"
            (constant_pool)
            (fields)
            (methods
                        (method "dispatchKeyEvent"
                              (parameters (class "java.awt.event.KeyEvent"))
                              (returntype . boolean)
                              (accessflags  *abstract*  *class*  *public* )
                              (code)))
            (interfaces)
            (accessflags  *abstract*  *interface*  *public* )
            (attributes
              (attribute "SourceFile")))))


(defconst *KeyEventDispatcher-class-table*
  (make-static-class-decls 
   *java.awt.KeyEventDispatcher*))

(defconst *package-name-map* 
  ("java.awt.KeyEventDispatcher" . "java.awt"))

