; IFn$ODOL-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:28:51 CDT 2014.
;

(defconst *clojure.lang.IFn$ODOL*
 (make-class-def
      '(class "clojure.lang.IFn$ODOL"
            "java.lang.Object"
            (constant_pool)
            (fields)
            (methods
                        (method "invokePrim"
                              (parameters (class "java.lang.Object") double (class "java.lang.Object"))
                              (returntype . long)
                              (accessflags  *abstract*  *class*  *public* )
                              (code)))
            (interfaces)
            (accessflags  *abstract*  *interface*  *public* )
            (attributes
              (attribute "SourceFile")
              (attribute "InnerClasses")))))


(defconst *IFn$ODOL-class-table*
  (make-static-class-decls 
   *clojure.lang.IFn$ODOL*))

(defconst *package-name-map* 
  ("clojure.lang.IFn$ODOL" . "clojure.lang"))

