; RT$3-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:28:53 CDT 2014.
;

(defconst *clojure.lang.RT$3*
 (make-class-def
      '(class "clojure.lang.RT$3"
            "clojure.lang.AFn"
            (constant_pool)
            (fields)
            (methods
                        (method "<init>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (invokespecial
					(methodCP "<init>" "clojure.lang.AFn" () void)))
                                      (4 (return))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke"
                              (parameters (class "java.lang.Object"))
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 3) (code_length . 14)
                                   (parsedcode
                                      (0 (aload_1)) ;;at TAG_0
                                      (1 (checkcast (class "java.lang.String"))) 
                                      (4 (invokestatic (methodCP "loadFile" "clojure.lang.Compiler" ((class "java.lang.String")) (class "java.lang.Object")))) 
                                      (7 (areturn)) ;;at TAG_1
                                      (8 (astore_2)) ;;at TAG_2
                                      (9 (aload_2)) 
                                      (10 (invokestatic (methodCP "sneakyThrow" "clojure.lang.Util" ((class "java.lang.Throwable")) (class "java.lang.RuntimeException")))) 
                                      (13 (athrow)) 
                                      (endofcode 14))
                                   (Exceptions 
                                     (handler 0 7  8 (class "java.io.IOException")))
                                   (StackMap ))))
            (interfaces)
            (accessflags  *class*  *final*  *super*  *synchronized* )
            (attributes
              (attribute "SourceFile")
              (attribute "EnclosingMethod")
              (attribute "InnerClasses")))))


(defconst *RT$3-class-table*
  (make-static-class-decls 
   *clojure.lang.RT$3*))

(defconst *package-name-map* 
  ("clojure.lang.RT$3" . "clojure.lang"))

