; NumberFormat-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:39:42 CDT 2014.
;

(defconst *java.text.NumberFormat*
 (make-class-def
      '(class "java.text.NumberFormat"
            "java.text.Format"
            (constant_pool
                        (INT 0)
                        (INT 1)
                        (INT 2)
                        (INT 3)
                        (INT 4)
                        (LONG -2308460125733713944)
                        (STRING  "Cannot format given Object as a Number")
                        (STRING  "Unparseable number: \"")
                        (STRING  "\"")
                        (STRING  "NumberPatterns")
                        (STRING  "Digit count range invalid"))
            (fields
                        (field "INTEGER_FIELD" int (accessflags  *class*  *final*  *public*  *static* ) 0)
                        (field "FRACTION_FIELD" int (accessflags  *class*  *final*  *public*  *static* ) 1)
                        (field "cachedLocaleData" (class "java.util.Hashtable") (accessflags  *class*  *final*  *private*  *static* ) -1)
                        (field "NUMBERSTYLE" int (accessflags  *class*  *final*  *private*  *static* ) 0)
                        (field "CURRENCYSTYLE" int (accessflags  *class*  *final*  *private*  *static* ) 1)
                        (field "PERCENTSTYLE" int (accessflags  *class*  *final*  *private*  *static* ) 2)
                        (field "SCIENTIFICSTYLE" int (accessflags  *class*  *final*  *private*  *static* ) 3)
                        (field "INTEGERSTYLE" int (accessflags  *class*  *final*  *private*  *static* ) 4)
                        (field "groupingUsed" boolean (accessflags  *class*  *private* ) -1)
                        (field "maxIntegerDigits" byte (accessflags  *class*  *private* ) -1)
                        (field "minIntegerDigits" byte (accessflags  *class*  *private* ) -1)
                        (field "maxFractionDigits" byte (accessflags  *class*  *private* ) -1)
                        (field "minFractionDigits" byte (accessflags  *class*  *private* ) -1)
                        (field "parseIntegerOnly" boolean (accessflags  *class*  *private* ) -1)
                        (field "maximumIntegerDigits" int (accessflags  *class*  *private* ) -1)
                        (field "minimumIntegerDigits" int (accessflags  *class*  *private* ) -1)
                        (field "maximumFractionDigits" int (accessflags  *class*  *private* ) -1)
                        (field "minimumFractionDigits" int (accessflags  *class*  *private* ) -1)
                        (field "currentSerialVersion" int (accessflags  *class*  *final*  *static* ) 1)
                        (field "serialVersionOnStream" int (accessflags  *class*  *private* ) -1)
                        (field "serialVersionUID" long (accessflags  *class*  *final*  *static* ) 5))
            (methods
                        (method "<init>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *protected* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 62)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (invokespecial
					(methodCP "<init>" "java.text.Format" () void)))
                                      (4 (aload_0))
                                      (5 (iconst_1))
                                      (6 (putfield (fieldCP "groupingUsed" "java.text.NumberFormat" boolean)))
                                      (9 (aload_0))
                                      (10 (bipush 40))
                                      (12 (putfield (fieldCP "maxIntegerDigits" "java.text.NumberFormat" byte)))
                                      (15 (aload_0))
                                      (16 (iconst_1))
                                      (17 (putfield (fieldCP "minIntegerDigits" "java.text.NumberFormat" byte)))
                                      (20 (aload_0))
                                      (21 (iconst_3))
                                      (22 (putfield (fieldCP "maxFractionDigits" "java.text.NumberFormat" byte)))
                                      (25 (aload_0))
                                      (26 (iconst_0))
                                      (27 (putfield (fieldCP "minFractionDigits" "java.text.NumberFormat" byte)))
                                      (30 (aload_0))
                                      (31 (iconst_0))
                                      (32 (putfield (fieldCP "parseIntegerOnly" "java.text.NumberFormat" boolean)))
                                      (35 (aload_0))
                                      (36 (bipush 40))
                                      (38 (putfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int)))
                                      (41 (aload_0))
                                      (42 (iconst_1))
                                      (43 (putfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int)))
                                      (46 (aload_0))
                                      (47 (iconst_3))
                                      (48 (putfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int)))
                                      (51 (aload_0))
                                      (52 (iconst_0))
                                      (53 (putfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int)))
                                      (56 (aload_0))
                                      (57 (iconst_1))
                                      (58 (putfield (fieldCP "serialVersionOnStream" "java.text.NumberFormat" int)))
                                      (61 (return))
                                      (endofcode 62))
                                   (Exceptions )
                                   (StackMap )))
                        (method "format"
                              (parameters (class "java.lang.Object") (class "java.lang.StringBuffer") (class "java.text.FieldPosition"))
                              (returntype . (class "java.lang.StringBuffer"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 5) (max_locals . 4) (code_length . 106)
                                   (parsedcode
                                      (0 (aload_1)) 
                                      (1 (instanceof (class "java.lang.Long"))) 
                                      (4 (ifne 61)) ;;to TAG_0
                                      (7 (aload_1)) 
                                      (8 (instanceof (class "java.lang.Integer"))) 
                                      (11 (ifne 61)) ;;to TAG_0
                                      (14 (aload_1)) 
                                      (15 (instanceof (class "java.lang.Short"))) 
                                      (18 (ifne 61)) ;;to TAG_0
                                      (21 (aload_1)) 
                                      (22 (instanceof (class "java.lang.Byte"))) 
                                      (25 (ifne 61)) ;;to TAG_0
                                      (28 (aload_1)) 
                                      (29 (instanceof (class "java.util.concurrent.atomic.AtomicInteger"))) 
                                      (32 (ifne 61)) ;;to TAG_0
                                      (35 (aload_1)) 
                                      (36 (instanceof (class "java.util.concurrent.atomic.AtomicLong"))) 
                                      (39 (ifne 61)) ;;to TAG_0
                                      (42 (aload_1)) 
                                      (43 (instanceof (class "java.math.BigInteger"))) 
                                      (46 (ifeq 75)) ;;to TAG_1
                                      (49 (aload_1)) 
                                      (50 (checkcast (class "java.math.BigInteger"))) 
                                      (53 (invokevirtual (methodCP "bitLength" "java.math.BigInteger" () int))) 
                                      (56 (bipush 64)) 
                                      (58 (if_icmpge 75)) ;;to TAG_1
                                      (61 (aload_0)) ;;at TAG_0
                                      (62 (aload_1)) 
                                      (63 (checkcast (class "java.lang.Number"))) 
                                      (66 (invokevirtual (methodCP "longValue" "java.lang.Number" () long))) 
                                      (69 (aload_2)) 
                                      (70 (aload_3)) 
                                      (71 (invokevirtual (methodCP "format" "java.text.NumberFormat" (long (class "java.lang.StringBuffer") (class "java.text.FieldPosition")) (class "java.lang.StringBuffer")))) 
                                      (74 (areturn)) 
                                      (75 (aload_1)) ;;at TAG_1
                                      (76 (instanceof (class "java.lang.Number"))) 
                                      (79 (ifeq 96))  ;;to TAG_2
                                      (82 (aload_0)) 
                                      (83 (aload_1)) 
                                      (84 (checkcast (class "java.lang.Number"))) 
                                      (87 (invokevirtual (methodCP "doubleValue" "java.lang.Number" () double))) 
                                      (90 (aload_2)) 
                                      (91 (aload_3)) 
                                      (92 (invokevirtual (methodCP "format" "java.text.NumberFormat" (double (class "java.lang.StringBuffer") (class "java.text.FieldPosition")) (class "java.lang.StringBuffer")))) 
                                      (95 (areturn)) 
                                      (96 (new (class "java.lang.IllegalArgumentException"))) ;;at TAG_2
                                      (99 (dup)) 
                                      (100 (ldc 6)) ;;STRING:: "Cannot format given Object as a Number"
                                      (102 (invokespecial (methodCP "<init>" "java.lang.IllegalArgumentException" ((class "java.lang.String")) void))) 
                                      (105 (athrow)) 
                                      (endofcode 106))
                                   (Exceptions )
                                   (StackMap )))
                        (method "parseObject"
                              (parameters (class "java.lang.String") (class "java.text.ParsePosition"))
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *final*  *public* )
                              (code
                                   (max_stack . 3) (max_locals . 3) (code_length . 7)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (aload_1))
                                      (2 (aload_2))
                                      (3 (invokevirtual
					(methodCP "parse" "java.text.NumberFormat" ((class "java.lang.String") (class "java.text.ParsePosition")) (class "java.lang.Number"))))
                                      (6 (areturn))
                                      (endofcode 7))
                                   (Exceptions )
                                   (StackMap )))
                        (method "format"
                              (parameters double)
                              (returntype . (class "java.lang.String"))
                              (accessflags  *class*  *final*  *public* )
                              (code
                                   (max_stack . 5) (max_locals . 3) (code_length . 19)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (dload_1))
                                      (2 (new (class "java.lang.StringBuffer")))
                                      (5 (dup))
                                      (6 (invokespecial
					(methodCP "<init>" "java.lang.StringBuffer" () void)))
                                      (9 (getstatic (fieldCP "INSTANCE" "java.text.DontCareFieldPosition" (class "java.text.FieldPosition"))))
                                      (12 (invokevirtual
					(methodCP "format" "java.text.NumberFormat" (double (class "java.lang.StringBuffer") (class "java.text.FieldPosition")) (class "java.lang.StringBuffer"))))
                                      (15 (invokevirtual
					(methodCP "toString" "java.lang.StringBuffer" () (class "java.lang.String"))))
                                      (18 (areturn))
                                      (endofcode 19))
                                   (Exceptions )
                                   (StackMap )))
                        (method "format"
                              (parameters long)
                              (returntype . (class "java.lang.String"))
                              (accessflags  *class*  *final*  *public* )
                              (code
                                   (max_stack . 5) (max_locals . 3) (code_length . 19)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (lload_1))
                                      (2 (new (class "java.lang.StringBuffer")))
                                      (5 (dup))
                                      (6 (invokespecial
					(methodCP "<init>" "java.lang.StringBuffer" () void)))
                                      (9 (getstatic (fieldCP "INSTANCE" "java.text.DontCareFieldPosition" (class "java.text.FieldPosition"))))
                                      (12 (invokevirtual
					(methodCP "format" "java.text.NumberFormat" (long (class "java.lang.StringBuffer") (class "java.text.FieldPosition")) (class "java.lang.StringBuffer"))))
                                      (15 (invokevirtual
					(methodCP "toString" "java.lang.StringBuffer" () (class "java.lang.String"))))
                                      (18 (areturn))
                                      (endofcode 19))
                                   (Exceptions )
                                   (StackMap )))
                        (method "format"
                              (parameters double (class "java.lang.StringBuffer") (class "java.text.FieldPosition"))
                              (returntype . (class "java.lang.StringBuffer"))
                              (accessflags  *abstract*  *class*  *public* )
                              (code))
                        (method "format"
                              (parameters long (class "java.lang.StringBuffer") (class "java.text.FieldPosition"))
                              (returntype . (class "java.lang.StringBuffer"))
                              (accessflags  *abstract*  *class*  *public* )
                              (code))
                        (method "parse"
                              (parameters (class "java.lang.String") (class "java.text.ParsePosition"))
                              (returntype . (class "java.lang.Number"))
                              (accessflags  *abstract*  *class*  *public* )
                              (code))
                        (method "parse"
                              (parameters (class "java.lang.String"))
                              (returntype . (class "java.lang.Number"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 4) (max_locals . 4) (code_length . 61)
                                   (parsedcode
                                      (0 (new (class "java.text.ParsePosition"))) 
                                      (3 (dup)) 
                                      (4 (iconst_0)) 
                                      (5 (invokespecial (methodCP "<init>" "java.text.ParsePosition" (int) void))) 
                                      (8 (astore_2)) 
                                      (9 (aload_0)) 
                                      (10 (aload_1)) 
                                      (11 (aload_2)) 
                                      (12 (invokevirtual (methodCP "parse" "java.text.NumberFormat" ((class "java.lang.String") (class "java.text.ParsePosition")) (class "java.lang.Number")))) 
                                      (15 (astore_3)) 
                                      (16 (aload_2)) 
                                      (17 (getfield (fieldCP "index" "java.text.ParsePosition" int))) 
                                      (20 (ifne 59))  ;;to TAG_0
                                      (23 (new (class "java.text.ParseException"))) 
                                      (26 (dup)) 
                                      (27 (new (class "java.lang.StringBuilder"))) 
                                      (30 (dup)) 
                                      (31 (invokespecial (methodCP "<init>" "java.lang.StringBuilder" () void))) 
                                      (34 (ldc 7)) ;;STRING:: "Unparseable number: \""
                                      (36 (invokevirtual (methodCP "append" "java.lang.StringBuilder" ((class "java.lang.String")) (class "java.lang.StringBuilder")))) 
                                      (39 (aload_1)) 
                                      (40 (invokevirtual (methodCP "append" "java.lang.StringBuilder" ((class "java.lang.String")) (class "java.lang.StringBuilder")))) 
                                      (43 (ldc 8)) ;;STRING:: "\""
                                      (45 (invokevirtual (methodCP "append" "java.lang.StringBuilder" ((class "java.lang.String")) (class "java.lang.StringBuilder")))) 
                                      (48 (invokevirtual (methodCP "toString" "java.lang.StringBuilder" () (class "java.lang.String")))) 
                                      (51 (aload_2)) 
                                      (52 (getfield (fieldCP "errorIndex" "java.text.ParsePosition" int))) 
                                      (55 (invokespecial (methodCP "<init>" "java.text.ParseException" ((class "java.lang.String") int) void))) 
                                      (58 (athrow)) 
                                      (59 (aload_3)) ;;at TAG_0
                                      (60 (areturn)) 
                                      (endofcode 61))
                                   (Exceptions )
                                   (StackMap )))
                        (method "isParseIntegerOnly"
                              (parameters )
                              (returntype . boolean)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "parseIntegerOnly" "java.text.NumberFormat" boolean)))
                                      (4 (ireturn))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "setParseIntegerOnly"
                              (parameters boolean)
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 2) (code_length . 6)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (iload_1))
                                      (2 (putfield (fieldCP "parseIntegerOnly" "java.text.NumberFormat" boolean)))
                                      (5 (return))
                                      (endofcode 6))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getInstance"
                              (parameters )
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *final*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 0) (code_length . 11)
                                   (parsedcode
                                      (0 (getstatic (fieldCP "FORMAT" "java.util.Locale$Category" (class "java.util.Locale$Category"))))
                                      (3 (invokestatic
					(methodCP "getDefault" "java.util.Locale" ((class "java.util.Locale$Category")) (class "java.util.Locale"))))
                                      (6 (iconst_0))
                                      (7 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (10 (areturn))
                                      (endofcode 11))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getInstance"
                              (parameters (class "java.util.Locale"))
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 6)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (iconst_0))
                                      (2 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (5 (areturn))
                                      (endofcode 6))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getNumberInstance"
                              (parameters )
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *final*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 0) (code_length . 11)
                                   (parsedcode
                                      (0 (getstatic (fieldCP "FORMAT" "java.util.Locale$Category" (class "java.util.Locale$Category"))))
                                      (3 (invokestatic
					(methodCP "getDefault" "java.util.Locale" ((class "java.util.Locale$Category")) (class "java.util.Locale"))))
                                      (6 (iconst_0))
                                      (7 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (10 (areturn))
                                      (endofcode 11))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getNumberInstance"
                              (parameters (class "java.util.Locale"))
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 6)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (iconst_0))
                                      (2 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (5 (areturn))
                                      (endofcode 6))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getIntegerInstance"
                              (parameters )
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *final*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 0) (code_length . 11)
                                   (parsedcode
                                      (0 (getstatic (fieldCP "FORMAT" "java.util.Locale$Category" (class "java.util.Locale$Category"))))
                                      (3 (invokestatic
					(methodCP "getDefault" "java.util.Locale" ((class "java.util.Locale$Category")) (class "java.util.Locale"))))
                                      (6 (iconst_4))
                                      (7 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (10 (areturn))
                                      (endofcode 11))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getIntegerInstance"
                              (parameters (class "java.util.Locale"))
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 6)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (iconst_4))
                                      (2 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (5 (areturn))
                                      (endofcode 6))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getCurrencyInstance"
                              (parameters )
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *final*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 0) (code_length . 11)
                                   (parsedcode
                                      (0 (getstatic (fieldCP "FORMAT" "java.util.Locale$Category" (class "java.util.Locale$Category"))))
                                      (3 (invokestatic
					(methodCP "getDefault" "java.util.Locale" ((class "java.util.Locale$Category")) (class "java.util.Locale"))))
                                      (6 (iconst_1))
                                      (7 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (10 (areturn))
                                      (endofcode 11))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getCurrencyInstance"
                              (parameters (class "java.util.Locale"))
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 6)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (iconst_1))
                                      (2 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (5 (areturn))
                                      (endofcode 6))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getPercentInstance"
                              (parameters )
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *final*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 0) (code_length . 11)
                                   (parsedcode
                                      (0 (getstatic (fieldCP "FORMAT" "java.util.Locale$Category" (class "java.util.Locale$Category"))))
                                      (3 (invokestatic
					(methodCP "getDefault" "java.util.Locale" ((class "java.util.Locale$Category")) (class "java.util.Locale"))))
                                      (6 (iconst_2))
                                      (7 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (10 (areturn))
                                      (endofcode 11))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getPercentInstance"
                              (parameters (class "java.util.Locale"))
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 6)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (iconst_2))
                                      (2 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (5 (areturn))
                                      (endofcode 6))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getScientificInstance"
                              (parameters )
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *final*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 0) (code_length . 11)
                                   (parsedcode
                                      (0 (getstatic (fieldCP "FORMAT" "java.util.Locale$Category" (class "java.util.Locale$Category"))))
                                      (3 (invokestatic
					(methodCP "getDefault" "java.util.Locale" ((class "java.util.Locale$Category")) (class "java.util.Locale"))))
                                      (6 (iconst_3))
                                      (7 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (10 (areturn))
                                      (endofcode 11))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getScientificInstance"
                              (parameters (class "java.util.Locale"))
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 6)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (iconst_3))
                                      (2 (invokestatic
					(methodCP "getInstance" "java.text.NumberFormat" ((class "java.util.Locale") int) (class "java.text.NumberFormat"))))
                                      (5 (areturn))
                                      (endofcode 6))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getAvailableLocales"
                              (parameters )
                              (returntype . (array (class "java.util.Locale")))
                              (accessflags  *class*  *public*  *static* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 12)
                                   (parsedcode
                                      (0 (ldc_w ))
                                      (3 (invokestatic
					(methodCP "getPool" "sun.util.LocaleServiceProviderPool" ((class "java.lang.Class")) (class "sun.util.LocaleServiceProviderPool"))))
                                      (6 (astore_0))
                                      (7 (aload_0))
                                      (8 (invokevirtual
					(methodCP "getAvailableLocales" "sun.util.LocaleServiceProviderPool" () (array (class "java.util.Locale")))))
                                      (11 (areturn))
                                      (endofcode 12))
                                   (Exceptions )
                                   (StackMap )))
                        (method "hashCode"
                              (parameters )
                              (returntype . int)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 13)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int)))
                                      (4 (bipush 37))
                                      (6 (imul))
                                      (7 (aload_0))
                                      (8 (getfield (fieldCP "maxFractionDigits" "java.text.NumberFormat" byte)))
                                      (11 (iadd))
                                      (12 (ireturn))
                                      (endofcode 13))
                                   (Exceptions )
                                   (StackMap )))
                        (method "equals"
                              (parameters (class "java.lang.Object"))
                              (returntype . boolean)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 3) (code_length . 103)
                                   (parsedcode
                                      (0 (aload_1)) 
                                      (1 (ifnonnull 6)) ;;to TAG_0
                                      (4 (iconst_0)) 
                                      (5 (ireturn)) 
                                      (6 (aload_0)) ;;at TAG_0
                                      (7 (aload_1)) 
                                      (8 (if_acmpne 13)) ;;to TAG_1
                                      (11 (iconst_1)) 
                                      (12 (ireturn)) 
                                      (13 (aload_0)) ;;at TAG_1
                                      (14 (invokevirtual (methodCP "getClass" "java.lang.Object" () (class "java.lang.Class")))) 
                                      (17 (aload_1)) 
                                      (18 (invokevirtual (methodCP "getClass" "java.lang.Object" () (class "java.lang.Class")))) 
                                      (21 (if_acmpeq 26))  ;;to TAG_2
                                      (24 (iconst_0)) 
                                      (25 (ireturn)) 
                                      (26 (aload_1)) ;;at TAG_2
                                      (27 (checkcast (class "java.text.NumberFormat"))) 
                                      (30 (astore_2)) 
                                      (31 (aload_0)) 
                                      (32 (getfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (35 (aload_2)) 
                                      (36 (getfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (39 (if_icmpne 101)) ;;to TAG_3
                                      (42 (aload_0)) 
                                      (43 (getfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (46 (aload_2)) 
                                      (47 (getfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (50 (if_icmpne 101)) ;;to TAG_3
                                      (53 (aload_0)) 
                                      (54 (getfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int))) 
                                      (57 (aload_2)) 
                                      (58 (getfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int))) 
                                      (61 (if_icmpne 101)) ;;to TAG_3
                                      (64 (aload_0)) 
                                      (65 (getfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (68 (aload_2)) 
                                      (69 (getfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (72 (if_icmpne 101)) ;;to TAG_3
                                      (75 (aload_0)) 
                                      (76 (getfield (fieldCP "groupingUsed" "java.text.NumberFormat" boolean))) 
                                      (79 (aload_2)) 
                                      (80 (getfield (fieldCP "groupingUsed" "java.text.NumberFormat" boolean))) 
                                      (83 (if_icmpne 101)) ;;to TAG_3
                                      (86 (aload_0)) 
                                      (87 (getfield (fieldCP "parseIntegerOnly" "java.text.NumberFormat" boolean))) 
                                      (90 (aload_2)) 
                                      (91 (getfield (fieldCP "parseIntegerOnly" "java.text.NumberFormat" boolean))) 
                                      (94 (if_icmpne 101)) ;;to TAG_3
                                      (97 (iconst_1)) 
                                      (98 (goto 102)) ;;to TAG_4
                                      (101 (iconst_0)) ;;at TAG_3
                                      (102 (ireturn)) ;;at TAG_4
                                      (endofcode 103))
                                   (Exceptions )
                                   (StackMap )))
                        (method "clone"
                              (parameters )
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 2) (code_length . 10)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (invokespecial
					(methodCP "clone" "java.text.Format" () (class "java.lang.Object"))))
                                      (4 (checkcast (class "java.text.NumberFormat")))
                                      (7 (astore_1))
                                      (8 (aload_1))
                                      (9 (areturn))
                                      (endofcode 10))
                                   (Exceptions )
                                   (StackMap )))
                        (method "isGroupingUsed"
                              (parameters )
                              (returntype . boolean)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "groupingUsed" "java.text.NumberFormat" boolean)))
                                      (4 (ireturn))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "setGroupingUsed"
                              (parameters boolean)
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 2) (code_length . 6)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (iload_1))
                                      (2 (putfield (fieldCP "groupingUsed" "java.text.NumberFormat" boolean)))
                                      (5 (return))
                                      (endofcode 6))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getMaximumIntegerDigits"
                              (parameters )
                              (returntype . int)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int)))
                                      (4 (ireturn))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "setMaximumIntegerDigits"
                              (parameters int)
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 3) (max_locals . 2) (code_length . 29)
                                   (parsedcode
                                      (0 (aload_0)) 
                                      (1 (iconst_0)) 
                                      (2 (iload_1)) 
                                      (3 (invokestatic (methodCP "max" "java.lang.Math" (int int) int))) 
                                      (6 (putfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (9 (aload_0)) 
                                      (10 (getfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (13 (aload_0)) 
                                      (14 (getfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (17 (if_icmple 28))  ;;to TAG_0
                                      (20 (aload_0)) 
                                      (21 (aload_0)) 
                                      (22 (getfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (25 (putfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (28 (return)) ;;at TAG_0
                                      (endofcode 29))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getMinimumIntegerDigits"
                              (parameters )
                              (returntype . int)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int)))
                                      (4 (ireturn))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "setMinimumIntegerDigits"
                              (parameters int)
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 3) (max_locals . 2) (code_length . 29)
                                   (parsedcode
                                      (0 (aload_0)) 
                                      (1 (iconst_0)) 
                                      (2 (iload_1)) 
                                      (3 (invokestatic (methodCP "max" "java.lang.Math" (int int) int))) 
                                      (6 (putfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (9 (aload_0)) 
                                      (10 (getfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (13 (aload_0)) 
                                      (14 (getfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (17 (if_icmple 28))  ;;to TAG_0
                                      (20 (aload_0)) 
                                      (21 (aload_0)) 
                                      (22 (getfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (25 (putfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (28 (return)) ;;at TAG_0
                                      (endofcode 29))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getMaximumFractionDigits"
                              (parameters )
                              (returntype . int)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int)))
                                      (4 (ireturn))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "setMaximumFractionDigits"
                              (parameters int)
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 3) (max_locals . 2) (code_length . 29)
                                   (parsedcode
                                      (0 (aload_0)) 
                                      (1 (iconst_0)) 
                                      (2 (iload_1)) 
                                      (3 (invokestatic (methodCP "max" "java.lang.Math" (int int) int))) 
                                      (6 (putfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int))) 
                                      (9 (aload_0)) 
                                      (10 (getfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int))) 
                                      (13 (aload_0)) 
                                      (14 (getfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (17 (if_icmpge 28))  ;;to TAG_0
                                      (20 (aload_0)) 
                                      (21 (aload_0)) 
                                      (22 (getfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int))) 
                                      (25 (putfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (28 (return)) ;;at TAG_0
                                      (endofcode 29))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getMinimumFractionDigits"
                              (parameters )
                              (returntype . int)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (getfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int)))
                                      (4 (ireturn))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "setMinimumFractionDigits"
                              (parameters int)
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 3) (max_locals . 2) (code_length . 29)
                                   (parsedcode
                                      (0 (aload_0)) 
                                      (1 (iconst_0)) 
                                      (2 (iload_1)) 
                                      (3 (invokestatic (methodCP "max" "java.lang.Math" (int int) int))) 
                                      (6 (putfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (9 (aload_0)) 
                                      (10 (getfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int))) 
                                      (13 (aload_0)) 
                                      (14 (getfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (17 (if_icmpge 28))  ;;to TAG_0
                                      (20 (aload_0)) 
                                      (21 (aload_0)) 
                                      (22 (getfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (25 (putfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int))) 
                                      (28 (return)) ;;at TAG_0
                                      (endofcode 29))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getCurrency"
                              (parameters )
                              (returntype . (class "java.util.Currency"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 8)
                                   (parsedcode
                                      (0 (new (class "java.lang.UnsupportedOperationException")))
                                      (3 (dup))
                                      (4 (invokespecial
					(methodCP "<init>" "java.lang.UnsupportedOperationException" () void)))
                                      (7 (athrow))
                                      (endofcode 8))
                                   (Exceptions )
                                   (StackMap )))
                        (method "setCurrency"
                              (parameters (class "java.util.Currency"))
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 2) (code_length . 8)
                                   (parsedcode
                                      (0 (new (class "java.lang.UnsupportedOperationException")))
                                      (3 (dup))
                                      (4 (invokespecial
					(methodCP "<init>" "java.lang.UnsupportedOperationException" () void)))
                                      (7 (athrow))
                                      (endofcode 8))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getRoundingMode"
                              (parameters )
                              (returntype . (class "java.math.RoundingMode"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 1) (code_length . 8)
                                   (parsedcode
                                      (0 (new (class "java.lang.UnsupportedOperationException")))
                                      (3 (dup))
                                      (4 (invokespecial
					(methodCP "<init>" "java.lang.UnsupportedOperationException" () void)))
                                      (7 (athrow))
                                      (endofcode 8))
                                   (Exceptions )
                                   (StackMap )))
                        (method "setRoundingMode"
                              (parameters (class "java.math.RoundingMode"))
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 2) (code_length . 8)
                                   (parsedcode
                                      (0 (new (class "java.lang.UnsupportedOperationException")))
                                      (3 (dup))
                                      (4 (invokespecial
					(methodCP "<init>" "java.lang.UnsupportedOperationException" () void)))
                                      (7 (athrow))
                                      (endofcode 8))
                                   (Exceptions )
                                   (StackMap )))
                        (method "getInstance"
                              (parameters (class "java.util.Locale") int)
                              (returntype . (class "java.text.NumberFormat"))
                              (accessflags  *class*  *private*  *static* )
                              (code
                                   (max_stack . 7) (max_locals . 7) (code_length . 156)
                                   (parsedcode
                                      (0 (ldc_w )) 
                                      (3 (invokestatic (methodCP "getPool" "sun.util.LocaleServiceProviderPool" ((class "java.lang.Class")) (class "sun.util.LocaleServiceProviderPool")))) 
                                      (6 (astore_2)) 
                                      (7 (aload_2)) 
                                      (8 (invokevirtual (methodCP "hasProviders" "sun.util.LocaleServiceProviderPool" () boolean))) 
                                      (11 (ifeq 43)) ;;to TAG_0
                                      (14 (aload_2)) 
                                      (15 (invokestatic (methodCP "access$000" "java.text.NumberFormat$NumberFormatGetter" () (class "java.text.NumberFormat$NumberFormatGetter")))) 
                                      (18 (aload_0)) 
                                      (19 (iconst_1)) 
                                      (20 (anewarray (class "java.lang.Object"))) 
                                      (23 (dup)) 
                                      (24 (iconst_0)) 
                                      (25 (iload_1)) 
                                      (26 (invokestatic (methodCP "valueOf" "java.lang.Integer" (int) (class "java.lang.Integer")))) 
                                      (29 (aastore)) 
                                      (30 (invokevirtual (methodCP "getLocalizedObject" "sun.util.LocaleServiceProviderPool" ((class "sun.util.LocaleServiceProviderPool$LocalizedObjectGetter") (class "java.util.Locale") (array (class "java.lang.Object"))) (class "java.lang.Object")))) 
                                      (33 (checkcast (class "java.text.NumberFormat"))) 
                                      (36 (astore_3)) 
                                      (37 (aload_3)) 
                                      (38 (ifnull 43)) ;;to TAG_0
                                      (41 (aload_3)) 
                                      (42 (areturn)) 
                                      (43 (getstatic (fieldCP "cachedLocaleData" "java.text.NumberFormat" (class "java.util.Hashtable")))) ;;at TAG_0
                                      (46 (aload_0)) 
                                      (47 (invokevirtual (methodCP "get" "java.util.Hashtable" ((class "java.lang.Object")) (class "java.lang.Object")))) 
                                      (50 (checkcast (array (class "java.lang.String")))) 
                                      (53 (checkcast (array (class "java.lang.String")))) 
                                      (56 (astore_3)) 
                                      (57 (aload_3)) 
                                      (58 (ifnonnull 84)) ;;to TAG_1
                                      (61 (aload_0)) 
                                      (62 (invokestatic (methodCP "getNumberFormatData" "sun.util.resources.LocaleData" ((class "java.util.Locale")) (class "java.util.ResourceBundle")))) 
                                      (65 (astore 4)) 
                                      (67 (aload 4)) 
                                      (69 (ldc 9)) ;;STRING:: "NumberPatterns"
                                      (71 (invokevirtual (methodCP "getStringArray" "java.util.ResourceBundle" ((class "java.lang.String")) (array (class "java.lang.String"))))) 
                                      (74 (astore_3)) 
                                      (75 (getstatic (fieldCP "cachedLocaleData" "java.text.NumberFormat" (class "java.util.Hashtable")))) 
                                      (78 (aload_0)) 
                                      (79 (aload_3)) 
                                      (80 (invokevirtual (methodCP "put" "java.util.Hashtable" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")))) 
                                      (83 (pop)) 
                                      (84 (aload_0)) ;;at TAG_1
                                      (85 (invokestatic (methodCP "getInstance" "java.text.DecimalFormatSymbols" ((class "java.util.Locale")) (class "java.text.DecimalFormatSymbols")))) 
                                      (88 (astore 4)) 
                                      (90 (iload_1)) 
                                      (91 (iconst_4)) 
                                      (92 (if_icmpne 99))  ;;to TAG_2
                                      (95 (iconst_0)) 
                                      (96 (goto 100)) ;;to TAG_3
                                      (99 (iload_1)) ;;at TAG_2
                                      (100 (istore 5)) ;;at TAG_3
                                      (102 (new (class "java.text.DecimalFormat"))) 
                                      (105 (dup)) 
                                      (106 (aload_3)) 
                                      (107 (iload 5)) 
                                      (109 (aaload)) 
                                      (110 (aload 4)) 
                                      (112 (invokespecial (methodCP "<init>" "java.text.DecimalFormat" ((class "java.lang.String") (class "java.text.DecimalFormatSymbols")) void))) 
                                      (115 (astore 6)) 
                                      (117 (iload_1)) 
                                      (118 (iconst_4)) 
                                      (119 (if_icmpne 143)) ;;to TAG_4
                                      (122 (aload 6)) 
                                      (124 (iconst_0)) 
                                      (125 (invokevirtual (methodCP "setMaximumFractionDigits" "java.text.DecimalFormat" (int) void))) 
                                      (128 (aload 6)) 
                                      (130 (iconst_0)) 
                                      (131 (invokevirtual (methodCP "setDecimalSeparatorAlwaysShown" "java.text.DecimalFormat" (boolean) void))) 
                                      (134 (aload 6)) 
                                      (136 (iconst_1)) 
                                      (137 (invokevirtual (methodCP "setParseIntegerOnly" "java.text.DecimalFormat" (boolean) void))) 
                                      (140 (goto 153)) ;;to TAG_5
                                      (143 (iload_1)) ;;at TAG_4
                                      (144 (iconst_1)) 
                                      (145 (if_icmpne 153)) ;;to TAG_5
                                      (148 (aload 6)) 
                                      (150 (invokevirtual (methodCP "adjustForCurrencyDefaultFractionDigits" "java.text.DecimalFormat" () void))) 
                                      (153 (aload 6)) ;;at TAG_5
                                      (155 (areturn)) 
                                      (endofcode 156))
                                   (Exceptions )
                                   (StackMap )))
                        (method "readObject"
                              (parameters (class "java.io.ObjectInputStream"))
                              (returntype . void)
                              (accessflags  *class*  *private* )
                              (code
                                   (max_stack . 3) (max_locals . 2) (code_length . 96)
                                   (parsedcode
                                      (0 (aload_1)) 
                                      (1 (invokevirtual (methodCP "defaultReadObject" "java.io.ObjectInputStream" () void))) 
                                      (4 (aload_0)) 
                                      (5 (getfield (fieldCP "serialVersionOnStream" "java.text.NumberFormat" int))) 
                                      (8 (iconst_1)) 
                                      (9 (if_icmpge 44)) ;;to TAG_0
                                      (12 (aload_0)) 
                                      (13 (aload_0)) 
                                      (14 (getfield (fieldCP "maxIntegerDigits" "java.text.NumberFormat" byte))) 
                                      (17 (putfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (20 (aload_0)) 
                                      (21 (aload_0)) 
                                      (22 (getfield (fieldCP "minIntegerDigits" "java.text.NumberFormat" byte))) 
                                      (25 (putfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (28 (aload_0)) 
                                      (29 (aload_0)) 
                                      (30 (getfield (fieldCP "maxFractionDigits" "java.text.NumberFormat" byte))) 
                                      (33 (putfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int))) 
                                      (36 (aload_0)) 
                                      (37 (aload_0)) 
                                      (38 (getfield (fieldCP "minFractionDigits" "java.text.NumberFormat" byte))) 
                                      (41 (putfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (44 (aload_0)) ;;at TAG_0
                                      (45 (getfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (48 (aload_0)) 
                                      (49 (getfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (52 (if_icmpgt 80)) ;;to TAG_1
                                      (55 (aload_0)) 
                                      (56 (getfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (59 (aload_0)) 
                                      (60 (getfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int))) 
                                      (63 (if_icmpgt 80)) ;;to TAG_1
                                      (66 (aload_0)) 
                                      (67 (getfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (70 (iflt 80)) ;;to TAG_1
                                      (73 (aload_0)) 
                                      (74 (getfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (77 (ifge 90))  ;;to TAG_2
                                      (80 (new (class "java.io.InvalidObjectException"))) ;;at TAG_1
                                      (83 (dup)) 
                                      (84 (ldc 10)) ;;STRING:: "Digit count range invalid"
                                      (86 (invokespecial (methodCP "<init>" "java.io.InvalidObjectException" ((class "java.lang.String")) void))) 
                                      (89 (athrow)) 
                                      (90 (aload_0)) ;;at TAG_2
                                      (91 (iconst_1)) 
                                      (92 (putfield (fieldCP "serialVersionOnStream" "java.text.NumberFormat" int))) 
                                      (95 (return)) 
                                      (endofcode 96))
                                   (Exceptions )
                                   (StackMap )))
                        (method "writeObject"
                              (parameters (class "java.io.ObjectOutputStream"))
                              (returntype . void)
                              (accessflags  *class*  *private* )
                              (code
                                   (max_stack . 3) (max_locals . 2) (code_length . 97)
                                   (parsedcode
                                      (0 (aload_0)) 
                                      (1 (aload_0)) 
                                      (2 (getfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (5 (bipush 127)) 
                                      (7 (if_icmple 15)) ;;to TAG_0
                                      (10 (bipush 127)) 
                                      (12 (goto 20)) ;;to TAG_1
                                      (15 (aload_0)) ;;at TAG_0
                                      (16 (getfield (fieldCP "maximumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (19 (i2b)) 
                                      (20 (putfield (fieldCP "maxIntegerDigits" "java.text.NumberFormat" byte))) ;;at TAG_1
                                      (23 (aload_0)) 
                                      (24 (aload_0)) 
                                      (25 (getfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (28 (bipush 127)) 
                                      (30 (if_icmple 38))  ;;to TAG_2
                                      (33 (bipush 127)) 
                                      (35 (goto 43)) ;;to TAG_3
                                      (38 (aload_0)) ;;at TAG_2
                                      (39 (getfield (fieldCP "minimumIntegerDigits" "java.text.NumberFormat" int))) 
                                      (42 (i2b)) 
                                      (43 (putfield (fieldCP "minIntegerDigits" "java.text.NumberFormat" byte))) ;;at TAG_3
                                      (46 (aload_0)) 
                                      (47 (aload_0)) 
                                      (48 (getfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int))) 
                                      (51 (bipush 127)) 
                                      (53 (if_icmple 61)) ;;to TAG_4
                                      (56 (bipush 127)) 
                                      (58 (goto 66)) ;;to TAG_5
                                      (61 (aload_0)) ;;at TAG_4
                                      (62 (getfield (fieldCP "maximumFractionDigits" "java.text.NumberFormat" int))) 
                                      (65 (i2b)) 
                                      (66 (putfield (fieldCP "maxFractionDigits" "java.text.NumberFormat" byte))) ;;at TAG_5
                                      (69 (aload_0)) 
                                      (70 (aload_0)) 
                                      (71 (getfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (74 (bipush 127)) 
                                      (76 (if_icmple 84)) ;;to TAG_6
                                      (79 (bipush 127)) 
                                      (81 (goto 89)) ;;to TAG_7
                                      (84 (aload_0)) ;;at TAG_6
                                      (85 (getfield (fieldCP "minimumFractionDigits" "java.text.NumberFormat" int))) 
                                      (88 (i2b)) 
                                      (89 (putfield (fieldCP "minFractionDigits" "java.text.NumberFormat" byte))) ;;at TAG_7
                                      (92 (aload_1)) 
                                      (93 (invokevirtual (methodCP "defaultWriteObject" "java.io.ObjectOutputStream" () void))) 
                                      (96 (return)) 
                                      (endofcode 97))
                                   (Exceptions )
                                   (StackMap )))
                        (method "<clinit>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *static* )
                              (code
                                   (max_stack . 3) (max_locals . 0) (code_length . 12)
                                   (parsedcode
                                      (0 (new (class "java.util.Hashtable")))
                                      (3 (dup))
                                      (4 (iconst_3))
                                      (5 (invokespecial
					(methodCP "<init>" "java.util.Hashtable" (int) void)))
                                      (8 (putstatic (fieldCP "cachedLocaleData" "java.text.NumberFormat" (class "java.util.Hashtable"))))
                                      (11 (return))
                                      (endofcode 12))
                                   (Exceptions )
                                   (StackMap ))))
            (interfaces)
            (accessflags  *abstract*  *class*  *public*  *super*  *synchronized* )
            (attributes
              (attribute "SourceFile")
              (attribute "InnerClasses")))))


(defconst *NumberFormat-class-table*
  (make-static-class-decls 
   *java.text.NumberFormat*))

(defconst *package-name-map* 
  ("java.text.NumberFormat" . "java.text"))

