; SystemClassLoaderAction-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:39:36 CDT 2014.
;

(defconst *java.lang.SystemClassLoaderAction*
 (make-class-def
      '(class "java.lang.SystemClassLoaderAction"
            "java.lang.Object"
            (constant_pool
                        (STRING  "java.system.class.loader"))
            (fields
                        (field "parent" (class "java.lang.ClassLoader") (accessflags  *class*  *private* ) -1))
            (methods
                        (method "<init>"
                              (parameters (class "java.lang.ClassLoader"))
                              (returntype . void)
                              (accessflags  *class* )
                              (code
                                   (max_stack . 2) (max_locals . 2) (code_length . 10)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (invokespecial
					(methodCP "<init>" "java.lang.Object" () void)))
                                      (4 (aload_0))
                                      (5 (aload_1))
                                      (6 (putfield (fieldCP "parent" "java.lang.SystemClassLoaderAction" (class "java.lang.ClassLoader"))))
                                      (9 (return))
                                      (endofcode 10))
                                   (Exceptions )
                                   (StackMap )))
                        (method "run"
                              (parameters )
                              (returntype . (class "java.lang.ClassLoader"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 5) (max_locals . 4) (code_length . 66)
                                   (parsedcode
                                      (0 (ldc 0)) ;;STRING:: "java.system.class.loader"
                                      (2 (invokestatic (methodCP "getProperty" "java.lang.System" ((class "java.lang.String")) (class "java.lang.String")))) 
                                      (5 (astore_1)) 
                                      (6 (aload_1)) 
                                      (7 (ifnonnull 15))  ;;to TAG_0
                                      (10 (aload_0)) 
                                      (11 (getfield (fieldCP "parent" "java.lang.SystemClassLoaderAction" (class "java.lang.ClassLoader")))) 
                                      (14 (areturn)) 
                                      (15 (aload_1)) ;;at TAG_0
                                      (16 (iconst_1)) 
                                      (17 (aload_0)) 
                                      (18 (getfield (fieldCP "parent" "java.lang.SystemClassLoaderAction" (class "java.lang.ClassLoader")))) 
                                      (21 (invokestatic (methodCP "forName" "java.lang.Class" ((class "java.lang.String") boolean (class "java.lang.ClassLoader")) (class "java.lang.Class")))) 
                                      (24 (iconst_1)) 
                                      (25 (anewarray (class "java.lang.Class"))) 
                                      (28 (dup)) 
                                      (29 (iconst_0)) 
                                      (30 (ldc_w )) 
                                      (33 (aastore)) 
                                      (34 (invokevirtual (methodCP "getDeclaredConstructor" "java.lang.Class" ((array (class "java.lang.Class"))) (class "java.lang.reflect.Constructor")))) 
                                      (37 (astore_2)) 
                                      (38 (aload_2)) 
                                      (39 (iconst_1)) 
                                      (40 (anewarray (class "java.lang.Object"))) 
                                      (43 (dup)) 
                                      (44 (iconst_0)) 
                                      (45 (aload_0)) 
                                      (46 (getfield (fieldCP "parent" "java.lang.SystemClassLoaderAction" (class "java.lang.ClassLoader")))) 
                                      (49 (aastore)) 
                                      (50 (invokevirtual (methodCP "newInstance" "java.lang.reflect.Constructor" ((array (class "java.lang.Object"))) (class "java.lang.Object")))) 
                                      (53 (checkcast (class "java.lang.ClassLoader"))) 
                                      (56 (astore_3)) 
                                      (57 (invokestatic (methodCP "currentThread" "java.lang.Thread" () (class "java.lang.Thread")))) 
                                      (60 (aload_3)) 
                                      (61 (invokevirtual (methodCP "setContextClassLoader" "java.lang.Thread" ((class "java.lang.ClassLoader")) void))) 
                                      (64 (aload_3)) 
                                      (65 (areturn)) 
                                      (endofcode 66))
                                   (Exceptions )
                                   (StackMap )))
                        (method "run"
                              (parameters )
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *public*  *volatile* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (invokevirtual
					(methodCP "run" "java.lang.SystemClassLoaderAction" () (class "java.lang.ClassLoader"))))
                                      (4 (areturn))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap ))))
            (interfaces "java.security.PrivilegedExceptionAction")
            (accessflags  *class*  *super*  *synchronized* )
            (attributes
              (attribute "SourceFile")
              (attribute "Signature")))))


(defconst *SystemClassLoaderAction-class-table*
  (make-static-class-decls 
   *java.lang.SystemClassLoaderAction*))

(defconst *package-name-map* 
  ("java.lang.SystemClassLoaderAction" . "java.lang"))

