; core$emit_method_builder-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:28:42 CDT 2014.
;

(defconst *clojure.core$emit_method_builder*
 (make-class-def
      '(class "clojure.core$emit_method_builder"
            "clojure.lang.AFunction"
            (constant_pool
                        (STRING  "clojure.core")
                        (STRING  "keyword")
                        (STRING  "with-meta")
                        (STRING  "gensym")
                        (STRING  "tag")
                        (STRING  "clojure.lang.AFunction")
                        (STRING  "seq")
                        (STRING  "concat")
                        (STRING  "list")
                        (STRING  "fn")
                        (STRING  "apply")
                        (STRING  "vector")
                        (STRING  "cache__5865__auto__")
                        (STRING  "let")
                        (STRING  "map")
                        (STRING  "f__5866__auto__")
                        (STRING  "hash-map")
                        (STRING  "set!")
                        (STRING  ".__methodImplCache"))
            (fields
                        (field "const__0" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__1" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__2" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__3" (class "clojure.lang.Keyword") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__4" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__5" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__6" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__7" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__8" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__9" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__10" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__11" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__12" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__13" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__14" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__15" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__16" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__17" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__18" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__19" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__20" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__21" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1))
            (methods
                        (method "<clinit>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *public*  *static* )
                              (code
                                   (max_stack . 5) (max_locals . 0) (code_length . 298)
                                   (parsedcode
                                      (0 (ldc 0))         ;;STRING:: "clojure.core"
                                      (2 (ldc 1))         ;;STRING:: "keyword"
                                      (4 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (7 (checkcast (class "clojure.lang.Var")))
                                      (10 (putstatic (fieldCP "const__0" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (13 (ldc 0))        ;;STRING:: "clojure.core"
                                      (15 (ldc 2))        ;;STRING:: "with-meta"
                                      (17 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (20 (checkcast (class "clojure.lang.Var")))
                                      (23 (putstatic (fieldCP "const__1" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (26 (ldc 0))        ;;STRING:: "clojure.core"
                                      (28 (ldc 3))        ;;STRING:: "gensym"
                                      (30 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (33 (checkcast (class "clojure.lang.Var")))
                                      (36 (putstatic (fieldCP "const__2" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (39 (aconst_null))
                                      (40 (ldc 4))        ;;STRING:: "tag"
                                      (42 (invokestatic
					(methodCP "keyword" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Keyword"))))
                                      (45 (checkcast (class "clojure.lang.Keyword")))
                                      (48 (putstatic (fieldCP "const__3" "clojure.core$emit_method_builder" (class "clojure.lang.Keyword"))))
                                      (51 (aconst_null))
                                      (52 (ldc 5))        ;;STRING:: "clojure.lang.AFunction"
                                      (54 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (57 (checkcast (class "clojure.lang.AFn")))
                                      (60 (putstatic (fieldCP "const__4" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (63 (iconst_2))
                                      (64 (anewarray (class "java.lang.Object")))
                                      (67 (dup))
                                      (68 (iconst_0))
                                      (69 (aconst_null))
                                      (70 (ldc 4))        ;;STRING:: "tag"
                                      (72 (invokestatic
					(methodCP "keyword" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Keyword"))))
                                      (75 (aastore))
                                      (76 (dup))
                                      (77 (iconst_1))
                                      (78 (aconst_null))
                                      (79 (ldc 5))        ;;STRING:: "clojure.lang.AFunction"
                                      (81 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (84 (aastore))
                                      (85 (invokestatic
					(methodCP "map" "clojure.lang.RT" ((array (class "java.lang.Object"))) (class "clojure.lang.IPersistentMap"))))
                                      (88 (checkcast (class "clojure.lang.AFn")))
                                      (91 (putstatic (fieldCP "const__5" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (94 (ldc 0))        ;;STRING:: "clojure.core"
                                      (96 (ldc 6))        ;;STRING:: "seq"
                                      (98 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (101 (checkcast (class "clojure.lang.Var")))
                                      (104 (putstatic (fieldCP "const__6" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (107 (ldc 0))       ;;STRING:: "clojure.core"
                                      (109 (ldc 7))       ;;STRING:: "concat"
                                      (111 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (114 (checkcast (class "clojure.lang.Var")))
                                      (117 (putstatic (fieldCP "const__7" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (120 (ldc 0))       ;;STRING:: "clojure.core"
                                      (122 (ldc 8))       ;;STRING:: "list"
                                      (124 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (127 (checkcast (class "clojure.lang.Var")))
                                      (130 (putstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (133 (ldc 0))       ;;STRING:: "clojure.core"
                                      (135 (ldc 9))       ;;STRING:: "fn"
                                      (137 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (140 (checkcast (class "clojure.lang.AFn")))
                                      (143 (putstatic (fieldCP "const__9" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (146 (ldc 0))       ;;STRING:: "clojure.core"
                                      (148 (ldc 10))      ;;STRING:: "apply"
                                      (150 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (153 (checkcast (class "clojure.lang.Var")))
                                      (156 (putstatic (fieldCP "const__10" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (159 (ldc 0))       ;;STRING:: "clojure.core"
                                      (161 (ldc 11))      ;;STRING:: "vector"
                                      (163 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (166 (checkcast (class "clojure.lang.Var")))
                                      (169 (putstatic (fieldCP "const__11" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (172 (aconst_null))
                                      (173 (ldc 12))      ;;STRING:: "cache__5865__auto__"
                                      (175 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (178 (checkcast (class "clojure.lang.AFn")))
                                      (181 (putstatic (fieldCP "const__12" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (184 (ldc 0))       ;;STRING:: "clojure.core"
                                      (186 (ldc 13))      ;;STRING:: "let"
                                      (188 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (191 (checkcast (class "clojure.lang.AFn")))
                                      (194 (putstatic (fieldCP "const__13" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (197 (ldc 0))       ;;STRING:: "clojure.core"
                                      (199 (ldc 9))       ;;STRING:: "fn"
                                      (201 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (204 (checkcast (class "clojure.lang.AFn")))
                                      (207 (putstatic (fieldCP "const__14" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (210 (ldc 0))       ;;STRING:: "clojure.core"
                                      (212 (ldc 14))      ;;STRING:: "map"
                                      (214 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (217 (checkcast (class "clojure.lang.Var")))
                                      (220 (putstatic (fieldCP "const__15" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (223 (aconst_null))
                                      (224 (ldc 15))      ;;STRING:: "f__5866__auto__"
                                      (226 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (229 (checkcast (class "clojure.lang.AFn")))
                                      (232 (putstatic (fieldCP "const__16" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (235 (ldc 0))       ;;STRING:: "clojure.core"
                                      (237 (ldc 16))      ;;STRING:: "hash-map"
                                      (239 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (242 (checkcast (class "clojure.lang.Var")))
                                      (245 (putstatic (fieldCP "const__17" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (248 (aconst_null))
                                      (249 (ldc 5))       ;;STRING:: "clojure.lang.AFunction"
                                      (251 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (254 (checkcast (class "clojure.lang.AFn")))
                                      (257 (putstatic (fieldCP "const__18" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (260 (ldc 0))       ;;STRING:: "clojure.core"
                                      (262 (ldc 9))       ;;STRING:: "fn"
                                      (264 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (267 (checkcast (class "clojure.lang.AFn")))
                                      (270 (putstatic (fieldCP "const__19" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (273 (aconst_null))
                                      (274 (ldc 17))      ;;STRING:: "set!"
                                      (276 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (279 (checkcast (class "clojure.lang.AFn")))
                                      (282 (putstatic (fieldCP "const__20" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (285 (aconst_null))
                                      (286 (ldc 18))      ;;STRING:: ".__methodImplCache"
                                      (288 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (291 (checkcast (class "clojure.lang.AFn")))
                                      (294 (putstatic (fieldCP "const__21" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (297 (return))
                                      (endofcode 298))
                                   (Exceptions )
                                   (StackMap )))
                        (method "<init>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (invokespecial
					(methodCP "<init>" "clojure.lang.AFunction" () void)))
                                      (4 (return))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object"))
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 28) (max_locals . 8) (code_length . 813)
                                   (parsedcode
                                      (0 (getstatic (fieldCP "const__0" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (3 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (6 (checkcast (class "clojure.lang.IFn")))
                                      (9 (aload_2))
                                      (10 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (15 (astore 5))
                                      (17 (getstatic (fieldCP "const__1" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (20 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (23 (checkcast (class "clojure.lang.IFn")))
                                      (26 (getstatic (fieldCP "const__2" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (29 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (32 (checkcast (class "clojure.lang.IFn")))
                                      (35 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" () (class "java.lang.Object")) 1))
                                      (40 (getstatic (fieldCP "const__5" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (43 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (48 (astore 6))
                                      (50 (getstatic (fieldCP "const__2" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (53 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (56 (checkcast (class "clojure.lang.IFn")))
                                      (59 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" () (class "java.lang.Object")) 1))
                                      (64 (astore 7))
                                      (66 (getstatic (fieldCP "const__6" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (69 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (72 (checkcast (class "clojure.lang.IFn")))
                                      (75 (getstatic (fieldCP "const__7" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (78 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (81 (checkcast (class "clojure.lang.IFn")))
                                      (84 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (87 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (90 (checkcast (class "clojure.lang.IFn")))
                                      (93 (getstatic (fieldCP "const__9" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (96 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (101 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (104 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (107 (checkcast (class "clojure.lang.IFn")))
                                      (110 (getstatic (fieldCP "const__10" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (113 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (116 (checkcast (class "clojure.lang.IFn")))
                                      (119 (getstatic (fieldCP "const__11" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (122 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (125 (getstatic (fieldCP "const__6" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (128 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (131 (checkcast (class "clojure.lang.IFn")))
                                      (134 (getstatic (fieldCP "const__7" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (137 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (140 (checkcast (class "clojure.lang.IFn")))
                                      (143 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (146 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (149 (checkcast (class "clojure.lang.IFn")))
                                      (152 (getstatic (fieldCP "const__12" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (155 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (160 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (165 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (170 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (175 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (180 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (183 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (186 (checkcast (class "clojure.lang.IFn")))
                                      (189 (getstatic (fieldCP "const__6" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (192 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (195 (checkcast (class "clojure.lang.IFn")))
                                      (198 (getstatic (fieldCP "const__7" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (201 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (204 (checkcast (class "clojure.lang.IFn")))
                                      (207 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (210 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (213 (checkcast (class "clojure.lang.IFn")))
                                      (216 (getstatic (fieldCP "const__13" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (219 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (224 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (227 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (230 (checkcast (class "clojure.lang.IFn")))
                                      (233 (getstatic (fieldCP "const__10" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (236 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (239 (checkcast (class "clojure.lang.IFn")))
                                      (242 (getstatic (fieldCP "const__11" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (245 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (248 (getstatic (fieldCP "const__6" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (251 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (254 (checkcast (class "clojure.lang.IFn")))
                                      (257 (getstatic (fieldCP "const__7" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (260 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (263 (checkcast (class "clojure.lang.IFn")))
                                      (266 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (269 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (272 (checkcast (class "clojure.lang.IFn")))
                                      (275 (aload 7))
                                      (277 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (282 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (285 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (288 (checkcast (class "clojure.lang.IFn")))
                                      (291 (getstatic (fieldCP "const__6" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (294 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (297 (checkcast (class "clojure.lang.IFn")))
                                      (300 (getstatic (fieldCP "const__7" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (303 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (306 (checkcast (class "clojure.lang.IFn")))
                                      (309 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (312 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (315 (checkcast (class "clojure.lang.IFn")))
                                      (318 (getstatic (fieldCP "const__14" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (321 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (326 (getstatic (fieldCP "const__15" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (329 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (332 (checkcast (class "clojure.lang.IFn")))
                                      (335 (new (class "clojure.core$emit_method_builder$fn__5867")))
                                      (338 (dup))
                                      (339 (aload_2))
                                      (340 (aconst_null))
                                      (341 (astore_2))
                                      (342 (aload_3))
                                      (343 (aconst_null))
                                      (344 (astore_3))
                                      (345 (aload_1))
                                      (346 (invokespecial
					(methodCP "<init>" "clojure.core$emit_method_builder$fn__5867" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) void)))
                                      (349 (aload 4))
                                      (351 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (356 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (361 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (366 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (371 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (374 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (377 (checkcast (class "clojure.lang.IFn")))
                                      (380 (getstatic (fieldCP "const__1" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (383 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (386 (checkcast (class "clojure.lang.IFn")))
                                      (389 (getstatic (fieldCP "const__16" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (392 (getstatic (fieldCP "const__10" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (395 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (398 (checkcast (class "clojure.lang.IFn")))
                                      (401 (getstatic (fieldCP "const__17" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (404 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (407 (getstatic (fieldCP "const__6" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (410 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (413 (checkcast (class "clojure.lang.IFn")))
                                      (416 (getstatic (fieldCP "const__7" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (419 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (422 (checkcast (class "clojure.lang.IFn")))
                                      (425 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (428 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (431 (checkcast (class "clojure.lang.IFn")))
                                      (434 (getstatic (fieldCP "const__3" "clojure.core$emit_method_builder" (class "clojure.lang.Keyword"))))
                                      (437 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (442 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (445 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (448 (checkcast (class "clojure.lang.IFn")))
                                      (451 (getstatic (fieldCP "const__18" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (454 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (459 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (464 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (469 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (474 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (479 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (484 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (487 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (490 (checkcast (class "clojure.lang.IFn")))
                                      (493 (getstatic (fieldCP "const__6" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (496 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (499 (checkcast (class "clojure.lang.IFn")))
                                      (502 (getstatic (fieldCP "const__7" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (505 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (508 (checkcast (class "clojure.lang.IFn")))
                                      (511 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (514 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (517 (checkcast (class "clojure.lang.IFn")))
                                      (520 (getstatic (fieldCP "const__19" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (523 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (528 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (531 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (534 (checkcast (class "clojure.lang.IFn")))
                                      (537 (aload 6))
                                      (539 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (544 (getstatic (fieldCP "const__15" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (547 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (550 (checkcast (class "clojure.lang.IFn")))
                                      (553 (new (class "clojure.core$emit_method_builder$fn__5872")))
                                      (556 (dup))
                                      (557 (aload 7))
                                      (559 (aconst_null))
                                      (560 (astore 7))
                                      (562 (aload 6))
                                      (564 (aconst_null))
                                      (565 (astore 6))
                                      (567 (aload_1))
                                      (568 (aconst_null))
                                      (569 (astore_1))
                                      (570 (invokespecial
					(methodCP "<init>" "clojure.core$emit_method_builder$fn__5872" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) void)))
                                      (573 (aload 4))
                                      (575 (aconst_null))
                                      (576 (astore 4))
                                      (578 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (583 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 4))
                                      (588 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (593 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (598 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 5))
                                      (603 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (608 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (613 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (618 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (621 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (624 (checkcast (class "clojure.lang.IFn")))
                                      (627 (getstatic (fieldCP "const__6" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (630 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (633 (checkcast (class "clojure.lang.IFn")))
                                      (636 (getstatic (fieldCP "const__7" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (639 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (642 (checkcast (class "clojure.lang.IFn")))
                                      (645 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (648 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (651 (checkcast (class "clojure.lang.IFn")))
                                      (654 (getstatic (fieldCP "const__20" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (657 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (662 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (665 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (668 (checkcast (class "clojure.lang.IFn")))
                                      (671 (getstatic (fieldCP "const__6" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (674 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (677 (checkcast (class "clojure.lang.IFn")))
                                      (680 (getstatic (fieldCP "const__7" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (683 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (686 (checkcast (class "clojure.lang.IFn")))
                                      (689 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (692 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (695 (checkcast (class "clojure.lang.IFn")))
                                      (698 (getstatic (fieldCP "const__21" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (701 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (706 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (709 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (712 (checkcast (class "clojure.lang.IFn")))
                                      (715 (getstatic (fieldCP "const__16" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (718 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (723 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (728 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (733 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (738 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (741 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (744 (checkcast (class "clojure.lang.IFn")))
                                      (747 (getstatic (fieldCP "const__12" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (750 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (755 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 4))
                                      (760 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (765 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (770 (getstatic (fieldCP "const__8" "clojure.core$emit_method_builder" (class "clojure.lang.Var"))))
                                      (773 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (776 (checkcast (class "clojure.lang.IFn")))
                                      (779 (getstatic (fieldCP "const__16" "clojure.core$emit_method_builder" (class "clojure.lang.AFn"))))
                                      (782 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (787 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 5))
                                      (792 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (797 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (802 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 4))
                                      (807 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (812 (areturn))
                                      (endofcode 813))
                                   (Exceptions )
                                   (StackMap ))))
            (interfaces)
            (accessflags  *class*  *final*  *public*  *super*  *synchronized* )
            (attributes
              (attribute "SourceFile")
              (attribute "SourceDebugExtension")))))


(defconst *core$emit_method_builder-class-table*
  (make-static-class-decls 
   *clojure.core$emit_method_builder*))

(defconst *package-name-map* 
  ("clojure.core$emit_method_builder" . "clojure"))

