; core$deref_future-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:28:41 CDT 2014.
;

(defconst *clojure.core$deref_future*
 (make-class-def
      '(class "clojure.core$deref_future"
            "clojure.lang.AFunction"
            (constant_pool)
            (fields)
            (methods
                        (method "<clinit>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *public*  *static* )
                              (code
                                   (max_stack . 0) (max_locals . 0) (code_length . 1)
                                   (parsedcode
                                      (0 (return))
                                      (endofcode 1))
                                   (Exceptions )
                                   (StackMap )))
                        (method "<init>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (invokespecial
					(methodCP "<init>" "clojure.lang.AFunction" () void)))
                                      (4 (return))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object"))
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 4) (max_locals . 6) (code_length . 44)
                                   (parsedcode
                                      (0 (aload_1)) ;;at TAG_1
                                      (1 (aconst_null)) 
                                      (2 (astore_1)) 
                                      (3 (checkcast (class "java.util.concurrent.Future"))) 
                                      (6 (aload_2)) 
                                      (7 (aconst_null)) 
                                      (8 (astore_2)) 
                                      (9 (checkcast (class "java.lang.Number"))) 
                                      (12 (invokestatic (methodCP "longCast" "clojure.lang.RT" ((class "java.lang.Object")) long))) 
                                      (15 (getstatic (fieldCP "MILLISECONDS" "java.util.concurrent.TimeUnit" (class "java.util.concurrent.TimeUnit")))) 
                                      (18 (checkcast (class "java.util.concurrent.TimeUnit"))) 
                                      (21 (invokeinterface (methodCP "get" "java.util.concurrent.Future" (long (class "java.util.concurrent.TimeUnit")) (class "java.lang.Object")) 4)) 
                                      (26 (astore 4)) 
                                      (28 (goto 41)) ;;to TAG_0;;at TAG_2
                                      (31 (astore 5)) ;;at TAG_3
                                      (33 (aload_3)) 
                                      (34 (aconst_null)) 
                                      (35 (astore_3)) 
                                      (36 (astore 4)) 
                                      (38 (goto 41)) ;;to TAG_0
                                      (41 (aload 4)) ;;at TAG_0
                                      (43 (areturn)) 
                                      (endofcode 44))
                                   (Exceptions 
                                     (handler 0 28  31 (class "java.util.concurrent.TimeoutException")))
                                   (StackMap )))
                        (method "invoke"
                              (parameters (class "java.lang.Object"))
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 2) (max_locals . 2) (code_length . 12)
                                   (parsedcode
                                      (0 (aload_1))
                                      (1 (aconst_null))
                                      (2 (astore_1))
                                      (3 (checkcast (class "java.util.concurrent.Future")))
                                      (6 (invokeinterface
					(methodCP "get" "java.util.concurrent.Future" () (class "java.lang.Object")) 1))
                                      (11 (areturn))
                                      (endofcode 12))
                                   (Exceptions )
                                   (StackMap ))))
            (interfaces)
            (accessflags  *class*  *final*  *public*  *super*  *synchronized* )
            (attributes
              (attribute "SourceFile")
              (attribute "SourceDebugExtension")))))


(defconst *core$deref_future-class-table*
  (make-static-class-decls 
   *clojure.core$deref_future*))

(defconst *package-name-map* 
  ("clojure.core$deref_future" . "clojure"))

