; pprint$format_simple_cardinal-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:28:56 CDT 2014.
;

(defconst *clojure.pprint$format_simple_cardinal*
 (make-class-def
      '(class "clojure.pprint$format_simple_cardinal"
            "clojure.lang.AFunction"
            (constant_pool
                        (STRING  "clojure.core")
                        (STRING  "quot")
                        (LONG 100)
                        (STRING  "rem")
                        (STRING  "str")
                        (STRING  "pos?")
                        (STRING  "nth")
                        (STRING  "clojure.pprint")
                        (STRING  "english-cardinal-units")
                        (STRING  "<")
                        (LONG 20)
                        (LONG 10)
                        (STRING  "english-cardinal-tens")
                        (STRING  " hundred")
                        (STRING  " ")
                        (STRING  "-"))
            (fields
                        (field "const__0" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__1" (class "java.lang.Object") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__2" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__3" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__4" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__5" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__6" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__7" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__8" (class "java.lang.Object") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__9" (class "java.lang.Object") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__10" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1))
            (methods
                        (method "<clinit>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 0) (code_length . 132)
                                   (parsedcode
                                      (0 (ldc 0))         ;;STRING:: "clojure.core"
                                      (2 (ldc 1))         ;;STRING:: "quot"
                                      (4 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (7 (checkcast (class "clojure.lang.Var")))
                                      (10 (putstatic (fieldCP "const__0" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var"))))
                                      (13 (ldc2_w 2))     ;; LONG:: "100"
                                      (16 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (19 (putstatic (fieldCP "const__1" "clojure.pprint$format_simple_cardinal" (class "java.lang.Object"))))
                                      (22 (ldc 0))        ;;STRING:: "clojure.core"
                                      (24 (ldc 3))        ;;STRING:: "rem"
                                      (26 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (29 (checkcast (class "clojure.lang.Var")))
                                      (32 (putstatic (fieldCP "const__2" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var"))))
                                      (35 (ldc 0))        ;;STRING:: "clojure.core"
                                      (37 (ldc 4))        ;;STRING:: "str"
                                      (39 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (42 (checkcast (class "clojure.lang.Var")))
                                      (45 (putstatic (fieldCP "const__3" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var"))))
                                      (48 (ldc 0))        ;;STRING:: "clojure.core"
                                      (50 (ldc 5))        ;;STRING:: "pos?"
                                      (52 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (55 (checkcast (class "clojure.lang.Var")))
                                      (58 (putstatic (fieldCP "const__4" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var"))))
                                      (61 (ldc 0))        ;;STRING:: "clojure.core"
                                      (63 (ldc 6))        ;;STRING:: "nth"
                                      (65 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (68 (checkcast (class "clojure.lang.Var")))
                                      (71 (putstatic (fieldCP "const__5" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var"))))
                                      (74 (ldc 7))        ;;STRING:: "clojure.pprint"
                                      (76 (ldc 8))        ;;STRING:: "english-cardinal-units"
                                      (78 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (81 (checkcast (class "clojure.lang.Var")))
                                      (84 (putstatic (fieldCP "const__6" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var"))))
                                      (87 (ldc 0))        ;;STRING:: "clojure.core"
                                      (89 (ldc 9))        ;;STRING:: "<"
                                      (91 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (94 (checkcast (class "clojure.lang.Var")))
                                      (97 (putstatic (fieldCP "const__7" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var"))))
                                      (100 (ldc2_w 10))   ;; LONG:: "20"
                                      (103 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (106 (putstatic (fieldCP "const__8" "clojure.pprint$format_simple_cardinal" (class "java.lang.Object"))))
                                      (109 (ldc2_w 11))   ;; LONG:: "10"
                                      (112 (invokestatic
					(methodCP "valueOf" "java.lang.Long" (long) (class "java.lang.Long"))))
                                      (115 (putstatic (fieldCP "const__9" "clojure.pprint$format_simple_cardinal" (class "java.lang.Object"))))
                                      (118 (ldc 7))       ;;STRING:: "clojure.pprint"
                                      (120 (ldc 12))      ;;STRING:: "english-cardinal-tens"
                                      (122 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (125 (checkcast (class "clojure.lang.Var")))
                                      (128 (putstatic (fieldCP "const__10" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var"))))
                                      (131 (return))
                                      (endofcode 132))
                                   (Exceptions )
                                   (StackMap )))
                        (method "<init>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (invokespecial
					(methodCP "<init>" "clojure.lang.AFunction" () void)))
                                      (4 (return))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke"
                              (parameters (class "java.lang.Object"))
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 9) (max_locals . 7) (code_length . 287)
                                   (parsedcode
                                      (0 (aload_1)) 
                                      (1 (ldc2_w 2)) ;; LONG:: "100"
                                      (4 (invokestatic (methodCP "quotient" "clojure.lang.Numbers" ((class "java.lang.Object") long) (class "java.lang.Number")))) 
                                      (7 (astore_2)) 
                                      (8 (aload_1)) 
                                      (9 (aconst_null)) 
                                      (10 (astore_1)) 
                                      (11 (ldc2_w 2)) ;; LONG:: "100"
                                      (14 (invokestatic (methodCP "remainder" "clojure.lang.Numbers" ((class "java.lang.Object") long) (class "java.lang.Number")))) 
                                      (17 (astore_3)) 
                                      (18 (getstatic (fieldCP "const__3" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var")))) 
                                      (21 (invokevirtual (methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object")))) 
                                      (24 (checkcast (class "clojure.lang.IFn"))) 
                                      (27 (aload_2)) 
                                      (28 (invokestatic (methodCP "isPos" "clojure.lang.Numbers" ((class "java.lang.Object")) boolean))) 
                                      (31 (ifeq 70)) ;;to TAG_0
                                      (34 (getstatic (fieldCP "const__3" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var")))) 
                                      (37 (invokevirtual (methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object")))) 
                                      (40 (checkcast (class "clojure.lang.IFn"))) 
                                      (43 (getstatic (fieldCP "const__6" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var")))) 
                                      (46 (invokevirtual (methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object")))) 
                                      (49 (aload_2)) 
                                      (50 (checkcast (class "java.lang.Number"))) 
                                      (53 (invokestatic (methodCP "intCast" "clojure.lang.RT" ((class "java.lang.Object")) int))) 
                                      (56 (invokestatic (methodCP "nth" "clojure.lang.RT" ((class "java.lang.Object") int) (class "java.lang.Object")))) 
                                      (59 (ldc 13)) ;;STRING:: " hundred"
                                      (61 (invokeinterface (methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3)) 
                                      (66 (goto 71)) ;;to TAG_1
                                      (69 (pop)) 
                                      (70 (aconst_null)) ;;at TAG_0
                                      (71 (aload_2)) ;;at TAG_1
                                      (72 (aconst_null)) 
                                      (73 (astore_2)) 
                                      (74 (invokestatic (methodCP "isPos" "clojure.lang.Numbers" ((class "java.lang.Object")) boolean))) 
                                      (77 (istore 4)) 
                                      (79 (iload 4)) 
                                      (81 (ifeq 92)) ;;to TAG_2
                                      (84 (aload_3)) 
                                      (85 (invokestatic (methodCP "isPos" "clojure.lang.Numbers" ((class "java.lang.Object")) boolean))) 
                                      (88 (goto 94)) ;;to TAG_3
                                      (91 (pop)) 
                                      (92 (iload 4)) ;;at TAG_2
                                      (94 (ifeq 103)) ;;to TAG_4;;at TAG_3
                                      (97 (ldc 14)) ;;STRING:: " "
                                      (99 (goto 104)) ;;to TAG_5
                                      (102 (pop)) 
                                      (103 (aconst_null)) ;;at TAG_4
                                      (104 (aload_3)) ;;at TAG_5
                                      (105 (invokestatic (methodCP "isPos" "clojure.lang.Numbers" ((class "java.lang.Object")) boolean))) 
                                      (108 (ifeq 280)) ;;to TAG_6
                                      (111 (aload_3)) 
                                      (112 (ldc2_w 10)) ;; LONG:: "20"
                                      (115 (invokestatic (methodCP "lt" "clojure.lang.Numbers" ((class "java.lang.Object") long) boolean))) 
                                      (118 (ifeq 143)) ;;to TAG_7
                                      (121 (getstatic (fieldCP "const__6" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var")))) 
                                      (124 (invokevirtual (methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object")))) 
                                      (127 (aload_3)) 
                                      (128 (aconst_null)) 
                                      (129 (astore_3)) 
                                      (130 (checkcast (class "java.lang.Number"))) 
                                      (133 (invokestatic (methodCP "intCast" "clojure.lang.RT" ((class "java.lang.Object")) int))) 
                                      (136 (invokestatic (methodCP "nth" "clojure.lang.RT" ((class "java.lang.Object") int) (class "java.lang.Object")))) 
                                      (139 (goto 276)) ;;to TAG_8
                                      (142 (pop)) 
                                      (143 (aload_3)) ;;at TAG_7
                                      (144 (ldc2_w 11)) ;; LONG:: "10"
                                      (147 (invokestatic (methodCP "quotient" "clojure.lang.Numbers" ((class "java.lang.Object") long) (class "java.lang.Number")))) 
                                      (150 (astore 4)) 
                                      (152 (aload_3)) 
                                      (153 (aconst_null)) 
                                      (154 (astore_3)) 
                                      (155 (ldc2_w 11)) ;; LONG:: "10"
                                      (158 (invokestatic (methodCP "remainder" "clojure.lang.Numbers" ((class "java.lang.Object") long) (class "java.lang.Number")))) 
                                      (161 (astore 5)) 
                                      (163 (getstatic (fieldCP "const__3" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var")))) 
                                      (166 (invokevirtual (methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object")))) 
                                      (169 (checkcast (class "clojure.lang.IFn"))) 
                                      (172 (aload 4)) 
                                      (174 (invokestatic (methodCP "isPos" "clojure.lang.Numbers" ((class "java.lang.Object")) boolean))) 
                                      (177 (ifeq 201)) ;;to TAG_9
                                      (180 (getstatic (fieldCP "const__10" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var")))) 
                                      (183 (invokevirtual (methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object")))) 
                                      (186 (aload 4)) 
                                      (188 (checkcast (class "java.lang.Number"))) 
                                      (191 (invokestatic (methodCP "intCast" "clojure.lang.RT" ((class "java.lang.Object")) int))) 
                                      (194 (invokestatic (methodCP "nth" "clojure.lang.RT" ((class "java.lang.Object") int) (class "java.lang.Object")))) 
                                      (197 (goto 202)) ;;to TAG_10
                                      (200 (pop)) 
                                      (201 (aconst_null)) ;;at TAG_9
                                      (202 (aload 4)) ;;at TAG_10
                                      (204 (aconst_null)) 
                                      (205 (astore 4)) 
                                      (207 (invokestatic (methodCP "isPos" "clojure.lang.Numbers" ((class "java.lang.Object")) boolean))) 
                                      (210 (istore 6)) 
                                      (212 (iload 6)) 
                                      (214 (ifeq 226)) ;;to TAG_11
                                      (217 (aload 5)) 
                                      (219 (invokestatic (methodCP "isPos" "clojure.lang.Numbers" ((class "java.lang.Object")) boolean))) 
                                      (222 (goto 228)) ;;to TAG_12
                                      (225 (pop)) 
                                      (226 (iload 6)) ;;at TAG_11
                                      (228 (ifeq 237))  ;;to TAG_13;;at TAG_12
                                      (231 (ldc 15)) ;;STRING:: "-"
                                      (233 (goto 238)) ;;to TAG_14
                                      (236 (pop)) 
                                      (237 (aconst_null)) ;;at TAG_13
                                      (238 (aload 5)) ;;at TAG_14
                                      (240 (invokestatic (methodCP "isPos" "clojure.lang.Numbers" ((class "java.lang.Object")) boolean))) 
                                      (243 (ifeq 270)) ;;to TAG_15
                                      (246 (getstatic (fieldCP "const__6" "clojure.pprint$format_simple_cardinal" (class "clojure.lang.Var")))) 
                                      (249 (invokevirtual (methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object")))) 
                                      (252 (aload 5)) 
                                      (254 (aconst_null)) 
                                      (255 (astore 5)) 
                                      (257 (checkcast (class "java.lang.Number"))) 
                                      (260 (invokestatic (methodCP "intCast" "clojure.lang.RT" ((class "java.lang.Object")) int))) 
                                      (263 (invokestatic (methodCP "nth" "clojure.lang.RT" ((class "java.lang.Object") int) (class "java.lang.Object")))) 
                                      (266 (goto 271)) ;;to TAG_16
                                      (269 (pop)) 
                                      (270 (aconst_null)) ;;at TAG_15
                                      (271 (invokeinterface (methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 4)) ;;at TAG_16
                                      (276 (goto 281)) ;;to TAG_17;;at TAG_8
                                      (279 (pop)) 
                                      (280 (aconst_null)) ;;at TAG_6
                                      (281 (invokeinterface (methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 4)) ;;at TAG_17
                                      (286 (areturn)) 
                                      (endofcode 287))
                                   (Exceptions )
                                   (StackMap ))))
            (interfaces)
            (accessflags  *class*  *final*  *public*  *super*  *synchronized* )
            (attributes
              (attribute "SourceFile")
              (attribute "SourceDebugExtension")))))


(defconst *pprint$format_simple_cardinal-class-table*
  (make-static-class-decls 
   *clojure.pprint$format_simple_cardinal*))

(defconst *package-name-map* 
  ("clojure.pprint$format_simple_cardinal" . "clojure"))

