; pprint$formatter_out-classtable.lisp
; Automatically generated by jvm2acl2 on Tue May 27 00:28:56 CDT 2014.
;

(defconst *clojure.pprint$formatter_out*
 (make-class-def
      '(class "clojure.pprint$formatter_out"
            "clojure.lang.AFunction"
            (constant_pool
                        (STRING  "clojure.core")
                        (STRING  "seq")
                        (STRING  "concat")
                        (STRING  "list")
                        (STRING  "let")
                        (STRING  "apply")
                        (STRING  "vector")
                        (STRING  "format-in__8171__auto__")
                        (STRING  "cf__8172__auto__")
                        (STRING  "if")
                        (STRING  "string?")
                        (STRING  "var")
                        (STRING  "clojure.pprint")
                        (STRING  "cached-compile")
                        (STRING  "fn")
                        (STRING  "&")
                        (STRING  "args__8173__auto__")
                        (STRING  "navigator__8174__auto__")
                        (STRING  "init-navigator")
                        (STRING  "execute-format"))
            (fields
                        (field "const__0" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__1" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__2" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__3" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__4" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__5" (class "clojure.lang.Var") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__6" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__7" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__8" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__9" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__10" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__11" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__12" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__13" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__14" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__15" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__16" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__17" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1)
                        (field "const__18" (class "clojure.lang.AFn") (accessflags  *class*  *final*  *public*  *static* ) -1))
            (methods
                        (method "<clinit>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *public*  *static* )
                              (code
                                   (max_stack . 2) (max_locals . 0) (code_length . 241)
                                   (parsedcode
                                      (0 (ldc 0))         ;;STRING:: "clojure.core"
                                      (2 (ldc 1))         ;;STRING:: "seq"
                                      (4 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (7 (checkcast (class "clojure.lang.Var")))
                                      (10 (putstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (13 (ldc 0))        ;;STRING:: "clojure.core"
                                      (15 (ldc 2))        ;;STRING:: "concat"
                                      (17 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (20 (checkcast (class "clojure.lang.Var")))
                                      (23 (putstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (26 (ldc 0))        ;;STRING:: "clojure.core"
                                      (28 (ldc 3))        ;;STRING:: "list"
                                      (30 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (33 (checkcast (class "clojure.lang.Var")))
                                      (36 (putstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (39 (ldc 0))        ;;STRING:: "clojure.core"
                                      (41 (ldc 4))        ;;STRING:: "let"
                                      (43 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (46 (checkcast (class "clojure.lang.AFn")))
                                      (49 (putstatic (fieldCP "const__3" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (52 (ldc 0))        ;;STRING:: "clojure.core"
                                      (54 (ldc 5))        ;;STRING:: "apply"
                                      (56 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (59 (checkcast (class "clojure.lang.Var")))
                                      (62 (putstatic (fieldCP "const__4" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (65 (ldc 0))        ;;STRING:: "clojure.core"
                                      (67 (ldc 6))        ;;STRING:: "vector"
                                      (69 (invokestatic
					(methodCP "var" "clojure.lang.RT" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Var"))))
                                      (72 (checkcast (class "clojure.lang.Var")))
                                      (75 (putstatic (fieldCP "const__5" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (78 (aconst_null))
                                      (79 (ldc 7))        ;;STRING:: "format-in__8171__auto__"
                                      (81 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (84 (checkcast (class "clojure.lang.AFn")))
                                      (87 (putstatic (fieldCP "const__6" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (90 (aconst_null))
                                      (91 (ldc 8))        ;;STRING:: "cf__8172__auto__"
                                      (93 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (96 (checkcast (class "clojure.lang.AFn")))
                                      (99 (putstatic (fieldCP "const__7" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (102 (aconst_null))
                                      (103 (ldc 9))       ;;STRING:: "if"
                                      (105 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (108 (checkcast (class "clojure.lang.AFn")))
                                      (111 (putstatic (fieldCP "const__8" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (114 (ldc 0))       ;;STRING:: "clojure.core"
                                      (116 (ldc 10))      ;;STRING:: "string?"
                                      (118 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (121 (checkcast (class "clojure.lang.AFn")))
                                      (124 (putstatic (fieldCP "const__9" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (127 (aconst_null))
                                      (128 (ldc 11))      ;;STRING:: "var"
                                      (130 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (133 (checkcast (class "clojure.lang.AFn")))
                                      (136 (putstatic (fieldCP "const__10" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (139 (ldc 12))      ;;STRING:: "clojure.pprint"
                                      (141 (ldc 13))      ;;STRING:: "cached-compile"
                                      (143 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (146 (checkcast (class "clojure.lang.AFn")))
                                      (149 (putstatic (fieldCP "const__11" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (152 (ldc 0))       ;;STRING:: "clojure.core"
                                      (154 (ldc 14))      ;;STRING:: "fn"
                                      (156 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (159 (checkcast (class "clojure.lang.AFn")))
                                      (162 (putstatic (fieldCP "const__12" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (165 (aconst_null))
                                      (166 (ldc 15))      ;;STRING:: "&"
                                      (168 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (171 (checkcast (class "clojure.lang.AFn")))
                                      (174 (putstatic (fieldCP "const__13" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (177 (aconst_null))
                                      (178 (ldc 16))      ;;STRING:: "args__8173__auto__"
                                      (180 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (183 (checkcast (class "clojure.lang.AFn")))
                                      (186 (putstatic (fieldCP "const__14" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (189 (ldc 0))       ;;STRING:: "clojure.core"
                                      (191 (ldc 4))       ;;STRING:: "let"
                                      (193 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (196 (checkcast (class "clojure.lang.AFn")))
                                      (199 (putstatic (fieldCP "const__15" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (202 (aconst_null))
                                      (203 (ldc 17))      ;;STRING:: "navigator__8174__auto__"
                                      (205 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (208 (checkcast (class "clojure.lang.AFn")))
                                      (211 (putstatic (fieldCP "const__16" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (214 (ldc 12))      ;;STRING:: "clojure.pprint"
                                      (216 (ldc 18))      ;;STRING:: "init-navigator"
                                      (218 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (221 (checkcast (class "clojure.lang.AFn")))
                                      (224 (putstatic (fieldCP "const__17" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (227 (ldc 12))      ;;STRING:: "clojure.pprint"
                                      (229 (ldc 19))      ;;STRING:: "execute-format"
                                      (231 (invokestatic
					(methodCP "intern" "clojure.lang.Symbol" ((class "java.lang.String") (class "java.lang.String")) (class "clojure.lang.Symbol"))))
                                      (234 (checkcast (class "clojure.lang.AFn")))
                                      (237 (putstatic (fieldCP "const__18" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (240 (return))
                                      (endofcode 241))
                                   (Exceptions )
                                   (StackMap )))
                        (method "<init>"
                              (parameters )
                              (returntype . void)
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 1) (max_locals . 1) (code_length . 5)
                                   (parsedcode
                                      (0 (aload_0))
                                      (1 (invokespecial
					(methodCP "<init>" "clojure.lang.AFunction" () void)))
                                      (4 (return))
                                      (endofcode 5))
                                   (Exceptions )
                                   (StackMap )))
                        (method "invoke"
                              (parameters (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object"))
                              (returntype . (class "java.lang.Object"))
                              (accessflags  *class*  *public* )
                              (code
                                   (max_stack . 28) (max_locals . 4) (code_length . 1026)
                                   (parsedcode
                                      (0 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (3 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (6 (checkcast (class "clojure.lang.IFn")))
                                      (9 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (12 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (15 (checkcast (class "clojure.lang.IFn")))
                                      (18 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (21 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (24 (checkcast (class "clojure.lang.IFn")))
                                      (27 (getstatic (fieldCP "const__3" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (30 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (35 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (38 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (41 (checkcast (class "clojure.lang.IFn")))
                                      (44 (getstatic (fieldCP "const__4" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (47 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (50 (checkcast (class "clojure.lang.IFn")))
                                      (53 (getstatic (fieldCP "const__5" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (56 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (59 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (62 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (65 (checkcast (class "clojure.lang.IFn")))
                                      (68 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (71 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (74 (checkcast (class "clojure.lang.IFn")))
                                      (77 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (80 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (83 (checkcast (class "clojure.lang.IFn")))
                                      (86 (getstatic (fieldCP "const__6" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (89 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (94 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (97 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (100 (checkcast (class "clojure.lang.IFn")))
                                      (103 (aload_3))
                                      (104 (aconst_null))
                                      (105 (astore_3))
                                      (106 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (111 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (114 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (117 (checkcast (class "clojure.lang.IFn")))
                                      (120 (getstatic (fieldCP "const__7" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (123 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (128 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (131 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (134 (checkcast (class "clojure.lang.IFn")))
                                      (137 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (140 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (143 (checkcast (class "clojure.lang.IFn")))
                                      (146 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (149 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (152 (checkcast (class "clojure.lang.IFn")))
                                      (155 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (158 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (161 (checkcast (class "clojure.lang.IFn")))
                                      (164 (getstatic (fieldCP "const__8" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (167 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (172 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (175 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (178 (checkcast (class "clojure.lang.IFn")))
                                      (181 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (184 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (187 (checkcast (class "clojure.lang.IFn")))
                                      (190 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (193 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (196 (checkcast (class "clojure.lang.IFn")))
                                      (199 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (202 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (205 (checkcast (class "clojure.lang.IFn")))
                                      (208 (getstatic (fieldCP "const__9" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (211 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (216 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (219 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (222 (checkcast (class "clojure.lang.IFn")))
                                      (225 (getstatic (fieldCP "const__6" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (228 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (233 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (238 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (243 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (248 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (251 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (254 (checkcast (class "clojure.lang.IFn")))
                                      (257 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (260 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (263 (checkcast (class "clojure.lang.IFn")))
                                      (266 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (269 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (272 (checkcast (class "clojure.lang.IFn")))
                                      (275 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (278 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (281 (checkcast (class "clojure.lang.IFn")))
                                      (284 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (287 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (290 (checkcast (class "clojure.lang.IFn")))
                                      (293 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (296 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (299 (checkcast (class "clojure.lang.IFn")))
                                      (302 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (305 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (308 (checkcast (class "clojure.lang.IFn")))
                                      (311 (getstatic (fieldCP "const__10" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (314 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (319 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (322 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (325 (checkcast (class "clojure.lang.IFn")))
                                      (328 (getstatic (fieldCP "const__11" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (331 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (336 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (341 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (346 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (351 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (354 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (357 (checkcast (class "clojure.lang.IFn")))
                                      (360 (getstatic (fieldCP "const__6" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (363 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (368 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (373 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (378 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (383 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (386 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (389 (checkcast (class "clojure.lang.IFn")))
                                      (392 (getstatic (fieldCP "const__6" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (395 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (400 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 5))
                                      (405 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (410 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (415 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 5))
                                      (420 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (425 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (430 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (435 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (438 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (441 (checkcast (class "clojure.lang.IFn")))
                                      (444 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (447 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (450 (checkcast (class "clojure.lang.IFn")))
                                      (453 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (456 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (459 (checkcast (class "clojure.lang.IFn")))
                                      (462 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (465 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (468 (checkcast (class "clojure.lang.IFn")))
                                      (471 (getstatic (fieldCP "const__12" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (474 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (479 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (482 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (485 (checkcast (class "clojure.lang.IFn")))
                                      (488 (getstatic (fieldCP "const__4" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (491 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (494 (checkcast (class "clojure.lang.IFn")))
                                      (497 (getstatic (fieldCP "const__5" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (500 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (503 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (506 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (509 (checkcast (class "clojure.lang.IFn")))
                                      (512 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (515 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (518 (checkcast (class "clojure.lang.IFn")))
                                      (521 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (524 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (527 (checkcast (class "clojure.lang.IFn")))
                                      (530 (getstatic (fieldCP "const__13" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (533 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (538 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (541 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (544 (checkcast (class "clojure.lang.IFn")))
                                      (547 (getstatic (fieldCP "const__14" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (550 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (555 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (560 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (565 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (570 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (575 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (578 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (581 (checkcast (class "clojure.lang.IFn")))
                                      (584 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (587 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (590 (checkcast (class "clojure.lang.IFn")))
                                      (593 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (596 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (599 (checkcast (class "clojure.lang.IFn")))
                                      (602 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (605 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (608 (checkcast (class "clojure.lang.IFn")))
                                      (611 (getstatic (fieldCP "const__15" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (614 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (619 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (622 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (625 (checkcast (class "clojure.lang.IFn")))
                                      (628 (getstatic (fieldCP "const__4" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (631 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (634 (checkcast (class "clojure.lang.IFn")))
                                      (637 (getstatic (fieldCP "const__5" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (640 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (643 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (646 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (649 (checkcast (class "clojure.lang.IFn")))
                                      (652 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (655 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (658 (checkcast (class "clojure.lang.IFn")))
                                      (661 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (664 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (667 (checkcast (class "clojure.lang.IFn")))
                                      (670 (getstatic (fieldCP "const__16" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (673 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (678 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (681 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (684 (checkcast (class "clojure.lang.IFn")))
                                      (687 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (690 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (693 (checkcast (class "clojure.lang.IFn")))
                                      (696 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (699 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (702 (checkcast (class "clojure.lang.IFn")))
                                      (705 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (708 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (711 (checkcast (class "clojure.lang.IFn")))
                                      (714 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (717 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (720 (checkcast (class "clojure.lang.IFn")))
                                      (723 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (726 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (729 (checkcast (class "clojure.lang.IFn")))
                                      (732 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (735 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (738 (checkcast (class "clojure.lang.IFn")))
                                      (741 (getstatic (fieldCP "const__10" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (744 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (749 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (752 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (755 (checkcast (class "clojure.lang.IFn")))
                                      (758 (getstatic (fieldCP "const__17" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (761 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (766 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (771 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (776 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (781 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (784 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (787 (checkcast (class "clojure.lang.IFn")))
                                      (790 (getstatic (fieldCP "const__14" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (793 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (798 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (803 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (808 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (813 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (818 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (823 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (828 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (833 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (836 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (839 (checkcast (class "clojure.lang.IFn")))
                                      (842 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (845 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (848 (checkcast (class "clojure.lang.IFn")))
                                      (851 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (854 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (857 (checkcast (class "clojure.lang.IFn")))
                                      (860 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (863 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (866 (checkcast (class "clojure.lang.IFn")))
                                      (869 (getstatic (fieldCP "const__0" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (872 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (875 (checkcast (class "clojure.lang.IFn")))
                                      (878 (getstatic (fieldCP "const__1" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (881 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (884 (checkcast (class "clojure.lang.IFn")))
                                      (887 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (890 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (893 (checkcast (class "clojure.lang.IFn")))
                                      (896 (getstatic (fieldCP "const__10" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (899 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (904 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (907 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (910 (checkcast (class "clojure.lang.IFn")))
                                      (913 (getstatic (fieldCP "const__18" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (916 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (921 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 3))
                                      (926 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (931 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (936 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (939 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (942 (checkcast (class "clojure.lang.IFn")))
                                      (945 (getstatic (fieldCP "const__7" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (948 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (953 (getstatic (fieldCP "const__2" "clojure.pprint$formatter_out" (class "clojure.lang.Var"))))
                                      (956 (invokevirtual
					(methodCP "getRawRoot" "clojure.lang.Var" () (class "java.lang.Object"))))
                                      (959 (checkcast (class "clojure.lang.IFn")))
                                      (962 (getstatic (fieldCP "const__16" "clojure.pprint$formatter_out" (class "clojure.lang.AFn"))))
                                      (965 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (970 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 4))
                                      (975 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (980 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (985 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 4))
                                      (990 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (995 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (1000 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 4))
                                      (1005 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (1010 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (1015 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object") (class "java.lang.Object") (class "java.lang.Object")) (class "java.lang.Object")) 4))
                                      (1020 (invokeinterface
					(methodCP "invoke" "clojure.lang.IFn" ((class "java.lang.Object")) (class "java.lang.Object")) 2))
                                      (1025 (areturn))
                                      (endofcode 1026))
                                   (Exceptions )
                                   (StackMap ))))
            (interfaces)
            (accessflags  *class*  *final*  *public*  *super*  *synchronized* )
            (attributes
              (attribute "SourceFile")
              (attribute "SourceDebugExtension")))))


(defconst *pprint$formatter_out-class-table*
  (make-static-class-decls 
   *clojure.pprint$formatter_out*))

(defconst *package-name-map* 
  ("clojure.pprint$formatter_out" . "clojure"))

